# Run Monte Carlo

In [35]:
from utopia.utopia import utopiaModel
import sys
import os
import requests
import pymongo
sys.path.insert(0, '../src')
from utopia.microservice.load_user_data.sampling import *

## Database configuration

In [36]:
#client = pymongo.MongoClient("mongodb://utopiauser:utopiapassword@localhost:27018/utopia?authSource=admin")
client = pymongo.MongoClient('mongodb://localhost:27017/')
db = client['utopia']
model_json_collection = db["model_json"]
interaction_collection = db["interaction"]
result_collection = db['result']
flow_collection = db['flow']
rate_constant_collection = db['rate_constant']
particle_state_collection = db['particle_state']
flow_estimation_collection = db['flow_estimation']
processed_result_collection = db['processed_result']
exposure_indicator_collection = db["exposure_indicator"]

## Load user data

In [37]:
data = utopiaModel.load_json_file("data/default_data.json")

In [38]:
param_distributions = {
    "MPdensity_kg_m3": ("lognorm", {"s": 0.05, "scale": np.exp(np.log(data["MPdensity_kg_m3"]) - (0.05**2) / 2)}),
    "FI": ("uniform", {"loc": 0.0, "scale": 1.0}),
    "t_half_deg_free": ("lognorm", {"s": 0.05, "scale": np.exp(np.log(data["t_half_deg_free"]) - (0.05**2) / 2)}),
    "t_frag_gen_FreeSurfaceWater": ("lognorm", {"s": 0.05, "scale": np.exp(np.log(data["t_frag_gen_FreeSurfaceWater"]) - (0.05**2) / 2)})
}

In [39]:
base_input = utopiaModel.load_json_file("data/default_data.json")
samples = generate_mc_samples(base_input, param_distributions, n_cases=100)

In [40]:
res = requests.post(
    "http://localhost:8001/input/batch",
    json={"data_list": samples}
)

input_ids = res.json()["input_ids"]
print("Generated input IDs:", input_ids)

Generated input IDs: ['6936eb6b714e757e129086c1', '6936eb6b714e757e129086c2', '6936eb6b714e757e129086c3', '6936eb6b714e757e129086c4', '6936eb6b714e757e129086c5', '6936eb6b714e757e129086c6', '6936eb6b714e757e129086c7', '6936eb6b714e757e129086c8', '6936eb6b714e757e129086c9', '6936eb6b714e757e129086ca', '6936eb6b714e757e129086cb', '6936eb6b714e757e129086cc', '6936eb6b714e757e129086cd', '6936eb6b714e757e129086ce', '6936eb6b714e757e129086cf', '6936eb6b714e757e129086d0', '6936eb6b714e757e129086d1', '6936eb6b714e757e129086d2', '6936eb6b714e757e129086d3', '6936eb6b714e757e129086d4', '6936eb6b714e757e129086d5', '6936eb6b714e757e129086d6', '6936eb6b714e757e129086d7', '6936eb6b714e757e129086d8', '6936eb6b714e757e129086d9', '6936eb6b714e757e129086da', '6936eb6b714e757e129086db', '6936eb6b714e757e129086dc', '6936eb6b714e757e129086dd', '6936eb6b714e757e129086de', '6936eb6b714e757e129086df', '6936eb6b714e757e129086e0', '6936eb6b714e757e129086e1', '6936eb6b714e757e129086e2', '6936eb6b714e757e129086e3', '6936eb6b714e757e129086e4', '6936eb6b714e757e129086e5', '6936eb6b714e757e129086e6', '6936eb6b714e757e129086e7', '6936eb6b714e757e129086e8', '6936eb6b714e757e129086e9', '6936eb6b714e757e129086ea', '6936eb6b714e757e129086eb', '6936eb6b714e757e129086ec', '6936eb6b714e757e129086ed', '6936eb6b714e757e129086ee', '6936eb6b714e757e129086ef', '6936eb6b714e757e129086f0', '6936eb6b714e757e129086f1', '6936eb6b714e757e129086f2', '6936eb6b714e757e129086f3', '6936eb6b714e757e129086f4', '6936eb6b714e757e129086f5', '6936eb6b714e757e129086f6', '6936eb6b714e757e129086f7', '6936eb6b714e757e129086f8', '6936eb6b714e757e129086f9', '6936eb6b714e757e129086fa', '6936eb6b714e757e129086fb', '6936eb6b714e757e129086fc', '6936eb6b714e757e129086fd', '6936eb6b714e757e129086fe', '6936eb6b714e757e129086ff', '6936eb6b714e757e12908700', '6936eb6b714e757e12908701', '6936eb6b714e757e12908702', '6936eb6b714e757e12908703', '6936eb6b714e757e12908704', '6936eb6b714e757e12908705', '6936eb6b714e757e12908706', '6936eb6b714e757e12908707', '6936eb6b714e757e12908708', '6936eb6b714e757e12908709', '6936eb6b714e757e1290870a', '6936eb6b714e757e1290870b', '6936eb6b714e757e1290870c', '6936eb6b714e757e1290870d', '6936eb6b714e757e1290870e', '6936eb6b714e757e1290870f', '6936eb6b714e757e12908710', '6936eb6b714e757e12908711', '6936eb6b714e757e12908712', '6936eb6b714e757e12908713', '6936eb6b714e757e12908714', '6936eb6b714e757e12908715', '6936eb6b714e757e12908716', '6936eb6b714e757e12908717', '6936eb6b714e757e12908718', '6936eb6b714e757e12908719', '6936eb6b714e757e1290871a', '6936eb6b714e757e1290871b', '6936eb6b714e757e1290871c', '6936eb6b714e757e1290871d', '6936eb6b714e757e1290871e', '6936eb6b714e757e1290871f', '6936eb6b714e757e12908720', '6936eb6b714e757e12908721', '6936eb6b714e757e12908722', '6936eb6b714e757e12908723', '6936eb6b714e757e12908724']

In [41]:
config_data = utopiaModel.load_json_file("data/default_config.json")
config_res = requests.post("http://localhost:8001/config", json={"data": config_data})
config_response = config_res.json()
config_id = config_response["config_id"]

print(config_res.json())

{'status': 'success', 'config_id': '6936eb6b714e757e12908725'}

## Generate objects

In [42]:
res = requests.post("http://localhost:8002/init_model_collections")
print(res.json())

{'status': 'model collection initialized'}

In [43]:
generate_res = requests.post(
    "http://localhost:8002/generate_object/batch", 
    json={
        "config_id": config_id,
        "input_ids": input_ids
    }
)
generate_response = generate_res.json()
print(generate_response)

{'status': 'success', 'model_ids': ['6936eb6cb19f000d48b1c862', '6936eb6cc77c0ff1798fce54', '6936eb6c35547f4955bed7bf', '6936eb6cfc480e63d6f0d47a', '6936eb6c35547f4955bed7c1', '6936eb6cb19f000d48b1c864', '6936eb6cfc480e63d6f0d47c', '6936eb6cc77c0ff1798fce56', '6936eb6c35547f4955bed7c3', '6936eb6cb19f000d48b1c866', '6936eb6cc77c0ff1798fce58', '6936eb6cfc480e63d6f0d47e', '6936eb6c35547f4955bed7c5', '6936eb6cb19f000d48b1c868', '6936eb6cc77c0ff1798fce5a', '6936eb6cfc480e63d6f0d480', '6936eb6c35547f4955bed7c7', '6936eb6cb19f000d48b1c86a', '6936eb6cc77c0ff1798fce5c', '6936eb6cfc480e63d6f0d482', '6936eb6c35547f4955bed7c9', '6936eb6cb19f000d48b1c86c', '6936eb6cc77c0ff1798fce5e', '6936eb6cfc480e63d6f0d484', '6936eb6d35547f4955bed7cb', '6936eb6db19f000d48b1c86e', '6936eb6dc77c0ff1798fce60', '6936eb6dfc480e63d6f0d486', '6936eb6d35547f4955bed7cd', '6936eb6db19f000d48b1c870', '6936eb6dc77c0ff1798fce62', '6936eb6dfc480e63d6f0d488', '6936eb6d35547f4955bed7cf', '6936eb6db19f000d48b1c872', '6936eb6dc77c0ff1798fce64', '6936eb6dfc480e63d6f0d48a', '6936eb6d35547f4955bed7d1', '6936eb6db19f000d48b1c874', '6936eb6dc77c0ff1798fce66', '6936eb6dfc480e63d6f0d48c', '6936eb6d35547f4955bed7d3', '6936eb6db19f000d48b1c876', '6936eb6dc77c0ff1798fce68', '6936eb6dfc480e63d6f0d48e', '6936eb6d35547f4955bed7d5', '6936eb6db19f000d48b1c878', '6936eb6dc77c0ff1798fce6a', '6936eb6dfc480e63d6f0d490', '6936eb6d35547f4955bed7d7', '6936eb6db19f000d48b1c87a', '6936eb6dc77c0ff1798fce6c', '6936eb6efc480e63d6f0d492', '6936eb6e35547f4955bed7d9', '6936eb6eb19f000d48b1c87c', '6936eb6ec77c0ff1798fce6e', '6936eb6efc480e63d6f0d494', '6936eb6e35547f4955bed7db', '6936eb6eb19f000d48b1c87e', '6936eb6ec77c0ff1798fce70', '6936eb6efc480e63d6f0d496', '6936eb6e35547f4955bed7dd', '6936eb6eb19f000d48b1c880', '6936eb6ec77c0ff1798fce72', '6936eb6efc480e63d6f0d498', '6936eb6e35547f4955bed7df', '6936eb6eb19f000d48b1c882', '6936eb6ec77c0ff1798fce74', '6936eb6efc480e63d6f0d49a', '6936eb6e35547f4955bed7e1', '6936eb6eb19f000d48b1c884', '6936eb6ec77c0ff1798fce76', '6936eb6efc480e63d6f0d49c', '6936eb6e35547f4955bed7e3', '6936eb6ec77c0ff1798fce78', '6936eb6eb19f000d48b1c886', '6936eb6efc480e63d6f0d49e', '6936eb6f35547f4955bed7e5', '6936eb6fb19f000d48b1c888', '6936eb6fc77c0ff1798fce7a', '6936eb6ffc480e63d6f0d4a0', '6936eb6f35547f4955bed7e7', '6936eb6fb19f000d48b1c88a', '6936eb6fc77c0ff1798fce7c', '6936eb6ffc480e63d6f0d4a2', '6936eb6f35547f4955bed7e9', '6936eb6fb19f000d48b1c88c', '6936eb6fc77c0ff1798fce7e', '6936eb6ffc480e63d6f0d4a4', '6936eb6f35547f4955bed7eb', '6936eb6fb19f000d48b1c88e', '6936eb6fc77c0ff1798fce80', '6936eb6ffc480e63d6f0d4a6', '6936eb6f35547f4955bed7ed', '6936eb6fb19f000d48b1c890', '6936eb6fc77c0ff1798fce82', '6936eb6ffc480e63d6f0d4a8', '6936eb6f35547f4955bed7ef', '6936eb6fb19f000d48b1c892', '6936eb6fc77c0ff1798fce84', '6936eb6ffc480e63d6f0d4aa']}

## Generate rate constants

In [44]:
res = requests.post("http://localhost:8003/init_rate_constant_collection")
print(res.json())

{'status': 'success', 'message': 'All 100 rate constant records have been deleted.'}

In [45]:
model_ids = generate_response["model_ids"]
print(type(model_ids[0]))

<class 'str'>

In [46]:
generate_rate_constant_res = requests.post(
    "http://localhost:8003/generate_rate_constants/batch", 
    json= {
    "model_ids": model_ids
    })

if generate_rate_constant_res.ok:
    print("Response:", generate_rate_constant_res.json())
else:
    print("Error:", generate_rate_constant_res.status_code, generate_rate_constant_res.text)

Response: {'status': 'success', 'count': 100, 'results': [{'model_id': '6936eb6c35547f4955bed7bf', 'rate_constant_id': '6936eb71d60caf9447d46985'}, {'model_id': '6936eb6cfc480e63d6f0d47a', 'rate_constant_id': '6936eb71d60caf9447d4698e'}, {'model_id': '6936eb6c35547f4955bed7c1', 'rate_constant_id': '6936eb71d60caf9447d4699e'}, {'model_id': '6936eb6cb19f000d48b1c864', 'rate_constant_id': '6936eb71d60caf9447d469a6'}, {'model_id': '6936eb6cc77c0ff1798fce54', 'rate_constant_id': '6936eb71d60caf9447d469af'}, {'model_id': '6936eb6c35547f4955bed7c3', 'rate_constant_id': '6936eb71d60caf9447d469bf'}, {'model_id': '6936eb6cb19f000d48b1c862', 'rate_constant_id': '6936eb71d60caf9447d469c4'}, {'model_id': '6936eb6cfc480e63d6f0d47c', 'rate_constant_id': '6936eb71d60caf9447d469d0'}, {'model_id': '6936eb6cc77c0ff1798fce56', 'rate_constant_id': '6936eb71d60caf9447d469d8'}, {'model_id': '6936eb6cc77c0ff1798fce58', 'rate_constant_id': '6936eb71d60caf9447d469db'}, {'model_id': '6936eb6cfc480e63d6f0d47e', 'rate_constant_id': '6936eb71d60caf9447d469e8'}, {'model_id': '6936eb6c35547f4955bed7c5', 'rate_constant_id': '6936eb71d60caf9447d469ef'}, {'model_id': '6936eb6cc77c0ff1798fce5a', 'rate_constant_id': '6936eb71d60caf9447d469f9'}, {'model_id': '6936eb6cb19f000d48b1c866', 'rate_constant_id': '6936eb71d60caf9447d469fa'}, {'model_id': '6936eb6cfc480e63d6f0d480', 'rate_constant_id': '6936eb71d60caf9447d46a05'}, {'model_id': '6936eb6c35547f4955bed7c7', 'rate_constant_id': '6936eb71d60caf9447d46a10'}, {'model_id': '6936eb6cb19f000d48b1c868', 'rate_constant_id': '6936eb71d60caf9447d46a13'}, {'model_id': '6936eb6cb19f000d48b1c86a', 'rate_constant_id': '6936eb71d60caf9447d46a15'}, {'model_id': '6936eb6cc77c0ff1798fce5c', 'rate_constant_id': '6936eb71d60caf9447d46a27'}, {'model_id': '6936eb6cfc480e63d6f0d482', 'rate_constant_id': '6936eb71d60caf9447d46a30'}, {'model_id': '6936eb6c35547f4955bed7c9', 'rate_constant_id': '6936eb71d60caf9447d46a34'}, {'model_id': '6936eb6cb19f000d48b1c86c', 'rate_constant_id': '6936eb71d60caf9447d46a35'}, {'model_id': '6936eb6cc77c0ff1798fce5e', 'rate_constant_id': '6936eb71d60caf9447d46a45'}, {'model_id': '6936eb6cfc480e63d6f0d484', 'rate_constant_id': '6936eb71d60caf9447d46a51'}, {'model_id': '6936eb6d35547f4955bed7cb', 'rate_constant_id': '6936eb71d60caf9447d46a52'}, {'model_id': '6936eb6db19f000d48b1c86e', 'rate_constant_id': '6936eb71d60caf9447d46a55'}, {'model_id': '6936eb6dc77c0ff1798fce60', 'rate_constant_id': '6936eb71d60caf9447d46a68'}, {'model_id': '6936eb6dfc480e63d6f0d486', 'rate_constant_id': '6936eb71d60caf9447d46a71'}, {'model_id': '6936eb6d35547f4955bed7cd', 'rate_constant_id': '6936eb71d60caf9447d46a72'}, {'model_id': '6936eb6db19f000d48b1c870', 'rate_constant_id': '6936eb71d60caf9447d46a76'}, {'model_id': '6936eb6dc77c0ff1798fce62', 'rate_constant_id': '6936eb71d60caf9447d46a85'}, {'model_id': '6936eb6dfc480e63d6f0d488', 'rate_constant_id': '6936eb71d60caf9447d46a91'}, {'model_id': '6936eb6d35547f4955bed7cf', 'rate_constant_id': '6936eb71d60caf9447d46a93'}, {'model_id': '6936eb6db19f000d48b1c872', 'rate_constant_id': '6936eb71d60caf9447d46a95'}, {'model_id': '6936eb6dc77c0ff1798fce64', 'rate_constant_id': '6936eb71d60caf9447d46a9e'}, {'model_id': '6936eb6db19f000d48b1c874', 'rate_constant_id': '6936eb71d60caf9447d46ab3'}, {'model_id': '6936eb6dfc480e63d6f0d48a', 'rate_constant_id': '6936eb71d60caf9447d46ab2'}, {'model_id': '6936eb6d35547f4955bed7d1', 'rate_constant_id': '6936eb71d60caf9447d46ab4'}, {'model_id': '6936eb6dc77c0ff1798fce66', 'rate_constant_id': '6936eb71d60caf9447d46ab9'}, {'model_id': '6936eb6dfc480e63d6f0d48c', 'rate_constant_id': '6936eb71d60caf9447d46ad2'}, {'model_id': '6936eb6d35547f4955bed7d3', 'rate_constant_id': '6936eb71d60caf9447d46ad3'}, {'model_id': '6936eb6db19f000d48b1c876', 'rate_constant_id': '6936eb71d60caf9447d46ad4'}, {'model_id': '6936eb6dc77c0ff1798fce68', 'rate_constant_id': '6936eb71d60caf9447d46ad9'}, {'model_id': '6936eb6db19f000d48b1c878', 'rate_constant_id': '6936eb71d60caf9447d46af0'}, {'model_id': '6936eb6d35547f4955bed7d5', 'rate_constant_id': '6936eb71d60caf9447d46af3'}, {'model_id': '6936eb6dfc480e63d6f0d48e', 'rate_constant_id': '6936eb71d60caf9447d46af5'}, {'model_id': '6936eb6dc77c0ff1798fce6a', 'rate_constant_id': '6936eb71d60caf9447d46af9'}, {'model_id': '6936eb6dfc480e63d6f0d490', 'rate_constant_id': '6936eb71d60caf9447d46b12'}, {'model_id': '6936eb6d35547f4955bed7d7', 'rate_constant_id': '6936eb71d60caf9447d46b13'}, {'model_id': '6936eb6db19f000d48b1c87a', 'rate_constant_id': '6936eb71d60caf9447d46b14'}, {'model_id': '6936eb6dc77c0ff1798fce6c', 'rate_constant_id': '6936eb71d60caf9447d46b19'}, {'model_id': '6936eb6eb19f000d48b1c87c', 'rate_constant_id': '6936eb71d60caf9447d46b33'}, {'model_id': '6936eb6efc480e63d6f0d492', 'rate_constant_id': '6936eb71d60caf9447d46b32'}, {'model_id': '6936eb6e35547f4955bed7d9', 'rate_constant_id': '6936eb71d60caf9447d46b34'}, {'model_id': '6936eb6ec77c0ff1798fce6e', 'rate_constant_id': '6936eb71d60caf9447d46b39'}, {'model_id': '6936eb6eb19f000d48b1c87e', 'rate_constant_id': '6936eb71d60caf9447d46b54'}, {'model_id': '6936eb6ec77c0ff1798fce70', 'rate_constant_id': '6936eb71d60caf9447d46b55'}, {'model_id': '6936eb6e35547f4955bed7db', 'rate_constant_id': '6936eb71d60caf9447d46b56'}, {'model_id': '6936eb6efc480e63d6f0d494', 'rate_constant_id': '6936eb71d60caf9447d46b51'}, {'model_id': '6936eb6e35547f4955bed7dd', 'rate_constant_id': '6936eb71d60caf9447d46b72'}, {'model_id': '6936eb6eb19f000d48b1c880', 'rate_constant_id': '6936eb71d60caf9447d46b73'}, {'model_id': '6936eb6efc480e63d6f0d496', 'rate_constant_id': '6936eb71d60caf9447d46b74'}, {'model_id': '6936eb6ec77c0ff1798fce72', 'rate_constant_id': '6936eb71d60caf9447d46b79'}, {'model_id': '6936eb6efc480e63d6f0d498', 'rate_constant_id': '6936eb71d60caf9447d46b93'}, {'model_id': '6936eb6ec77c0ff1798fce74', 'rate_constant_id': '6936eb71d60caf9447d46b95'}, {'model_id': '6936eb6eb19f000d48b1c882', 'rate_constant_id': '6936eb71d60caf9447d46b94'}, {'model_id': '6936eb6e35547f4955bed7df', 'rate_constant_id': '6936eb71d60caf9447d46b96'}, {'model_id': '6936eb6eb19f000d48b1c884', 'rate_constant_id': '6936eb71d60caf9447d46bb4'}, {'model_id': '6936eb6ec77c0ff1798fce76', 'rate_constant_id': '6936eb71d60caf9447d46bb2'}, {'model_id': '6936eb6e35547f4955bed7e1', 'rate_constant_id': '6936eb71d60caf9447d46bb3'}, {'model_id': '6936eb6efc480e63d6f0d49a', 'rate_constant_id': '6936eb71d60caf9447d46bb9'}, {'model_id': '6936eb6eb19f000d48b1c886', 'rate_constant_id': '6936eb71d60caf9447d46bd2'}, {'model_id': '6936eb6efc480e63d6f0d49c', 'rate_constant_id': '6936eb71d60caf9447d46bd3'}, {'model_id': '6936eb6e35547f4955bed7e3', 'rate_constant_id': '6936eb71d60caf9447d46bd5'}, {'model_id': '6936eb6ec77c0ff1798fce78', 'rate_constant_id': '6936eb71d60caf9447d46bd6'}, {'model_id': '6936eb6f35547f4955bed7e5', 'rate_constant_id': '6936eb71d60caf9447d46bf0'}, {'model_id': '6936eb6efc480e63d6f0d49e', 'rate_constant_id': '6936eb71d60caf9447d46bf4'}, {'model_id': '6936eb6fb19f000d48b1c888', 'rate_constant_id': '6936eb71d60caf9447d46bfa'}, {'model_id': '6936eb6fc77c0ff1798fce7a', 'rate_constant_id': '6936eb71d60caf9447d46c05'}, {'model_id': '6936eb6ffc480e63d6f0d4a0', 'rate_constant_id': '6936eb71d60caf9447d46c10'}, {'model_id': '6936eb6f35547f4955bed7e7', 'rate_constant_id': '6936eb71d60caf9447d46c16'}, {'model_id': '6936eb6fb19f000d48b1c88a', 'rate_constant_id': '6936eb71d60caf9447d46c17'}, {'model_id': '6936eb6fc77c0ff1798fce7c', 'rate_constant_id': '6936eb71d60caf9447d46c28'}, {'model_id': '6936eb6ffc480e63d6f0d4a2', 'rate_constant_id': '6936eb71d60caf9447d46c2d'}, {'model_id': '6936eb6f35547f4955bed7e9', 'rate_constant_id': '6936eb71d60caf9447d46c35'}, {'model_id': '6936eb6fb19f000d48b1c88c', 'rate_constant_id': '6936eb71d60caf9447d46c37'}, {'model_id': '6936eb6fc77c0ff1798fce7e', 'rate_constant_id': '6936eb71d60caf9447d46c48'}, {'model_id': '6936eb6ffc480e63d6f0d4a4', 'rate_constant_id': '6936eb71d60caf9447d46c4b'}, {'model_id': '6936eb6f35547f4955bed7eb', 'rate_constant_id': '6936eb71d60caf9447d46c53'}, {'model_id': '6936eb6fb19f000d48b1c88e', 'rate_constant_id': '6936eb71d60caf9447d46c59'}, {'model_id': '6936eb6fc77c0ff1798fce80', 'rate_constant_id': '6936eb71d60caf9447d46c68'}, {'model_id': '6936eb6ffc480e63d6f0d4a6', 'rate_constant_id': '6936eb71d60caf9447d46c6b'}, {'model_id': '6936eb6f35547f4955bed7ed', 'rate_constant_id': '6936eb71d60caf9447d46c76'}, {'model_id': '6936eb6fb19f000d48b1c890', 'rate_constant_id': '6936eb71d60caf9447d46c74'}, {'model_id': '6936eb6fc77c0ff1798fce82', 'rate_constant_id': '6936eb71d60caf9447d46c88'}, {'model_id': '6936eb6ffc480e63d6f0d4a8', 'rate_constant_id': '6936eb71d60caf9447d46c8b'}, {'model_id': '6936eb6f35547f4955bed7ef', 'rate_constant_id': '6936eb71d60caf9447d46c95'}, {'model_id': '6936eb6fb19f000d48b1c892', 'rate_constant_id': '6936eb71d60caf9447d46c97'}, {'model_id': '6936eb6fc77c0ff1798fce84', 'rate_constant_id': '6936eb71d60caf9447d46c9e'}, {'model_id': '6936eb6ffc480e63d6f0d4aa', 'rate_constant_id': '6936eb71d60caf9447d46ca1'}]}

## generate interaction matrix

In [47]:
initialize_interaction_matrix_res = requests.post(
    "http://localhost:8005/init_interaction_matrix_collection", 
)
print(initialize_interaction_matrix_res)

<Response [200]>

In [48]:
interaction_matrix_res = requests.post(
    "http://localhost:8005/generate_interaction_matrix/batch", 
    json={
        "items":generate_rate_constant_res.json()["results"]
    }
)

if interaction_matrix_res.ok:
    print("Response:", interaction_matrix_res.json())
else:
    print("Error:", interaction_matrix_res.status_code, interaction_matrix_res.text)

Response: {'status': 'success', 'count': 100, 'successful': 100, 'failed': 0, 'results': [{'model_id': '6936eb6c35547f4955bed7bf', 'interaction_matrix_id': '6936eb74e3e8bfa0c63913f7', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cfc480e63d6f0d47a', 'interaction_matrix_id': '6936eb74e3e8bfa0c63913f8', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6c35547f4955bed7c1', 'interaction_matrix_id': '6936eb74e3e8bfa0c63913f9', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cb19f000d48b1c864', 'interaction_matrix_id': '6936eb74e3e8bfa0c63913fa', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cc77c0ff1798fce54', 'interaction_matrix_id': '6936eb75e3e8bfa0c63913fb', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6c35547f4955bed7c3', 'interaction_matrix_id': '6936eb75e3e8bfa0c63913fc', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cb19f000d48b1c862', 'interaction_matrix_id': '6936eb75e3e8bfa0c63913fd', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cfc480e63d6f0d47c', 'interaction_matrix_id': '6936eb75e3e8bfa0c63913fe', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cc77c0ff1798fce56', 'interaction_matrix_id': '6936eb76e3e8bfa0c63913ff', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cc77c0ff1798fce58', 'interaction_matrix_id': '6936eb76e3e8bfa0c6391400', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cfc480e63d6f0d47e', 'interaction_matrix_id': '6936eb76e3e8bfa0c6391401', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6c35547f4955bed7c5', 'interaction_matrix_id': '6936eb76e3e8bfa0c6391402', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cc77c0ff1798fce5a', 'interaction_matrix_id': '6936eb77e3e8bfa0c6391403', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cb19f000d48b1c866', 'interaction_matrix_id': '6936eb77e3e8bfa0c6391404', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6c35547f4955bed7c7', 'interaction_matrix_id': '6936eb77e3e8bfa0c6391405', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cfc480e63d6f0d480', 'interaction_matrix_id': '6936eb77e3e8bfa0c6391406', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cb19f000d48b1c868', 'interaction_matrix_id': '6936eb78e3e8bfa0c6391407', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cb19f000d48b1c86a', 'interaction_matrix_id': '6936eb78e3e8bfa0c6391408', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cc77c0ff1798fce5c', 'interaction_matrix_id': '6936eb78e3e8bfa0c6391409', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cfc480e63d6f0d482', 'interaction_matrix_id': '6936eb78e3e8bfa0c639140a', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6c35547f4955bed7c9', 'interaction_matrix_id': '6936eb78e3e8bfa0c639140b', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cb19f000d48b1c86c', 'interaction_matrix_id': '6936eb78e3e8bfa0c639140c', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cc77c0ff1798fce5e', 'interaction_matrix_id': '6936eb78e3e8bfa0c639140d', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6cfc480e63d6f0d484', 'interaction_matrix_id': '6936eb78e3e8bfa0c639140e', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6d35547f4955bed7cb', 'interaction_matrix_id': '6936eb79e3e8bfa0c639140f', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6db19f000d48b1c86e', 'interaction_matrix_id': '6936eb79e3e8bfa0c6391410', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dc77c0ff1798fce60', 'interaction_matrix_id': '6936eb79e3e8bfa0c6391411', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dfc480e63d6f0d486', 'interaction_matrix_id': '6936eb79e3e8bfa0c6391412', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6d35547f4955bed7cd', 'interaction_matrix_id': '6936eb7ae3e8bfa0c6391413', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6db19f000d48b1c870', 'interaction_matrix_id': '6936eb7ae3e8bfa0c6391414', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dc77c0ff1798fce62', 'interaction_matrix_id': '6936eb7ae3e8bfa0c6391415', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dfc480e63d6f0d488', 'interaction_matrix_id': '6936eb7ae3e8bfa0c6391416', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6d35547f4955bed7cf', 'interaction_matrix_id': '6936eb7be3e8bfa0c6391417', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6db19f000d48b1c872', 'interaction_matrix_id': '6936eb7be3e8bfa0c6391418', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dc77c0ff1798fce64', 'interaction_matrix_id': '6936eb7be3e8bfa0c6391419', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6db19f000d48b1c874', 'interaction_matrix_id': '6936eb7be3e8bfa0c639141a', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dfc480e63d6f0d48a', 'interaction_matrix_id': '6936eb7ce3e8bfa0c639141b', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6d35547f4955bed7d1', 'interaction_matrix_id': '6936eb7ce3e8bfa0c639141c', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dc77c0ff1798fce66', 'interaction_matrix_id': '6936eb7ce3e8bfa0c639141d', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dfc480e63d6f0d48c', 'interaction_matrix_id': '6936eb7ce3e8bfa0c639141e', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6d35547f4955bed7d3', 'interaction_matrix_id': '6936eb7ce3e8bfa0c639141f', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6db19f000d48b1c876', 'interaction_matrix_id': '6936eb7ce3e8bfa0c6391420', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dc77c0ff1798fce68', 'interaction_matrix_id': '6936eb7ce3e8bfa0c6391421', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6db19f000d48b1c878', 'interaction_matrix_id': '6936eb7ce3e8bfa0c6391422', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6d35547f4955bed7d5', 'interaction_matrix_id': '6936eb7de3e8bfa0c6391423', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dfc480e63d6f0d48e', 'interaction_matrix_id': '6936eb7de3e8bfa0c6391424', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dc77c0ff1798fce6a', 'interaction_matrix_id': '6936eb7de3e8bfa0c6391425', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dfc480e63d6f0d490', 'interaction_matrix_id': '6936eb7de3e8bfa0c6391426', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6d35547f4955bed7d7', 'interaction_matrix_id': '6936eb7ee3e8bfa0c6391427', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6db19f000d48b1c87a', 'interaction_matrix_id': '6936eb7ee3e8bfa0c6391428', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6dc77c0ff1798fce6c', 'interaction_matrix_id': '6936eb7ee3e8bfa0c6391429', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6eb19f000d48b1c87c', 'interaction_matrix_id': '6936eb7ee3e8bfa0c639142a', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6efc480e63d6f0d492', 'interaction_matrix_id': '6936eb7fe3e8bfa0c639142b', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6e35547f4955bed7d9', 'interaction_matrix_id': '6936eb7fe3e8bfa0c639142c', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ec77c0ff1798fce6e', 'interaction_matrix_id': '6936eb7fe3e8bfa0c639142d', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6eb19f000d48b1c87e', 'interaction_matrix_id': '6936eb7fe3e8bfa0c639142e', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ec77c0ff1798fce70', 'interaction_matrix_id': '6936eb80e3e8bfa0c639142f', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6e35547f4955bed7db', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391430', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6efc480e63d6f0d494', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391431', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6e35547f4955bed7dd', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391432', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6eb19f000d48b1c880', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391433', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6efc480e63d6f0d496', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391434', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ec77c0ff1798fce72', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391435', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6efc480e63d6f0d498', 'interaction_matrix_id': '6936eb81e3e8bfa0c6391436', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ec77c0ff1798fce74', 'interaction_matrix_id': '6936eb81e3e8bfa0c6391437', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6eb19f000d48b1c882', 'interaction_matrix_id': '6936eb81e3e8bfa0c6391438', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6e35547f4955bed7df', 'interaction_matrix_id': '6936eb81e3e8bfa0c6391439', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6eb19f000d48b1c884', 'interaction_matrix_id': '6936eb81e3e8bfa0c639143a', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ec77c0ff1798fce76', 'interaction_matrix_id': '6936eb82e3e8bfa0c639143b', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6e35547f4955bed7e1', 'interaction_matrix_id': '6936eb82e3e8bfa0c639143c', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6efc480e63d6f0d49a', 'interaction_matrix_id': '6936eb82e3e8bfa0c639143d', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6eb19f000d48b1c886', 'interaction_matrix_id': '6936eb82e3e8bfa0c639143e', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6efc480e63d6f0d49c', 'interaction_matrix_id': '6936eb83e3e8bfa0c639143f', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6e35547f4955bed7e3', 'interaction_matrix_id': '6936eb83e3e8bfa0c6391440', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ec77c0ff1798fce78', 'interaction_matrix_id': '6936eb83e3e8bfa0c6391441', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6f35547f4955bed7e5', 'interaction_matrix_id': '6936eb83e3e8bfa0c6391442', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6efc480e63d6f0d49e', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391443', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fb19f000d48b1c888', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391444', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fc77c0ff1798fce7a', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391445', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ffc480e63d6f0d4a0', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391446', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6f35547f4955bed7e7', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391447', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fb19f000d48b1c88a', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391448', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fc77c0ff1798fce7c', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391449', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ffc480e63d6f0d4a2', 'interaction_matrix_id': '6936eb85e3e8bfa0c639144a', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6f35547f4955bed7e9', 'interaction_matrix_id': '6936eb85e3e8bfa0c639144b', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fb19f000d48b1c88c', 'interaction_matrix_id': '6936eb85e3e8bfa0c639144c', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fc77c0ff1798fce7e', 'interaction_matrix_id': '6936eb85e3e8bfa0c639144d', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ffc480e63d6f0d4a4', 'interaction_matrix_id': '6936eb85e3e8bfa0c639144e', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6f35547f4955bed7eb', 'interaction_matrix_id': '6936eb86e3e8bfa0c639144f', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fb19f000d48b1c88e', 'interaction_matrix_id': '6936eb86e3e8bfa0c6391450', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fc77c0ff1798fce80', 'interaction_matrix_id': '6936eb86e3e8bfa0c6391451', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ffc480e63d6f0d4a6', 'interaction_matrix_id': '6936eb86e3e8bfa0c6391452', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6f35547f4955bed7ed', 'interaction_matrix_id': '6936eb87e3e8bfa0c6391453', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fb19f000d48b1c890', 'interaction_matrix_id': '6936eb87e3e8bfa0c6391454', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fc77c0ff1798fce82', 'interaction_matrix_id': '6936eb87e3e8bfa0c6391455', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ffc480e63d6f0d4a8', 'interaction_matrix_id': '6936eb87e3e8bfa0c6391456', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6f35547f4955bed7ef', 'interaction_matrix_id': '6936eb88e3e8bfa0c6391457', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fb19f000d48b1c892', 'interaction_matrix_id': '6936eb88e3e8bfa0c6391458', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6fc77c0ff1798fce84', 'interaction_matrix_id': '6936eb88e3e8bfa0c6391459', 'status': 'interaction matrix generated and saved to mongodb'}, {'model_id': '6936eb6ffc480e63d6f0d4aa', 'interaction_matrix_id': '6936eb88e3e8bfa0c639145a', 'status': 'interaction matrix generated and saved to mongodb'}]}

## Solve Steady State

In [49]:
res = requests.post("http://localhost:8006/init_result_collection")
print(res.json())

{'status': 'success', 'message': 'All 100 result records have been deleted.'}

In [50]:
res = requests.post("http://localhost:8006/init_flow_collection")
print(res.json())

{'status': 'success', 'message': 'All 100 flow records have been deleted.'}

In [51]:
res = requests.post("http://localhost:8006/init_particle_state_collection")
print(res.json())

{'status': 'success', 'message': 'All 100 particle state records have been deleted.'}

In [52]:
solve_steady_state_res = requests.post(
    "http://localhost:8006/solve_steady_state/batch",
    json = {
        "items": interaction_matrix_res.json()["results"]
    }
)
if solve_steady_state_res.ok:
    print("Response:", solve_steady_state_res.json())
else:
    print("Error:", solve_steady_state_res.status_code, solve_steady_state_res.text)

Response: {'total': 100, 'successful': 100, 'failed': 0, 'results': [{'model_id': '6936eb6c35547f4955bed7bf', 'result_id': '6936eb8a9e3b6d74b14801f1', 'flow_id': '6936eb8a9e3b6d74b14801f2', 'particle_state_id': '6936eb8a9e3b6d74b14801f0', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47a', 'result_id': '6936eb8a349471dcd59e8137', 'flow_id': '6936eb8a349471dcd59e8138', 'particle_state_id': '6936eb8a349471dcd59e8136', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c1', 'result_id': '6936eb935a6158019055c777', 'flow_id': '6936eb935a6158019055c778', 'particle_state_id': '6936eb935a6158019055c776', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c864', 'result_id': '6936eb933c1fa026c95e129f', 'flow_id': '6936eb933c1fa026c95e12a0', 'particle_state_id': '6936eb933c1fa026c95e129e', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce54', 'result_id': '6936eb8d748ae09978ac0bfd', 'flow_id': '6936eb8e748ae09978ac0bfe', 'particle_state_id': '6936eb8d748ae09978ac0bfc', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c3', 'result_id': '6936eb926a81281d3a277c71', 'flow_id': '6936eb926a81281d3a277c72', 'particle_state_id': '6936eb926a81281d3a277c70', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c862', 'result_id': '6936eb93c9896b2b194a8668', 'flow_id': '6936eb93c9896b2b194a8669', 'particle_state_id': '6936eb93c9896b2b194a8667', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47c', 'result_id': '6936eb92494a6e38d021b320', 'flow_id': '6936eb92494a6e38d021b321', 'particle_state_id': '6936eb92494a6e38d021b31f', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce56', 'result_id': '6936eb939e3b6d74b14801f4', 'flow_id': '6936eb939e3b6d74b14801f5', 'particle_state_id': '6936eb939e3b6d74b14801f3', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce58', 'result_id': '6936eb93349471dcd59e813a', 'flow_id': '6936eb93349471dcd59e813b', 'particle_state_id': '6936eb93349471dcd59e8139', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47e', 'result_id': '6936eb96748ae09978ac0c00', 'flow_id': '6936eb97748ae09978ac0c01', 'particle_state_id': '6936eb96748ae09978ac0bff', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c5', 'result_id': '6936eb9b6a81281d3a277c74', 'flow_id': '6936eb9b6a81281d3a277c75', 'particle_state_id': '6936eb9b6a81281d3a277c73', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5a', 'result_id': '6936eb9b494a6e38d021b323', 'flow_id': '6936eb9b494a6e38d021b324', 'particle_state_id': '6936eb9b494a6e38d021b322', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c866', 'result_id': '6936eb9cc9896b2b194a866b', 'flow_id': '6936eb9cc9896b2b194a866c', 'particle_state_id': '6936eb9cc9896b2b194a866a', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c7', 'result_id': '6936eb9c5a6158019055c77a', 'flow_id': '6936eb9c5a6158019055c77b', 'particle_state_id': '6936eb9c5a6158019055c779', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d480', 'result_id': '6936eb9c3c1fa026c95e12a2', 'flow_id': '6936eb9c3c1fa026c95e12a3', 'particle_state_id': '6936eb9c3c1fa026c95e12a1', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c868', 'result_id': '6936eb9d9e3b6d74b14801f7', 'flow_id': '6936eb9d9e3b6d74b14801f8', 'particle_state_id': '6936eb9d9e3b6d74b14801f6', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c86a', 'result_id': '6936eb9d349471dcd59e813d', 'flow_id': '6936eb9d349471dcd59e813e', 'particle_state_id': '6936eb9d349471dcd59e813c', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5c', 'result_id': '6936eba1748ae09978ac0c03', 'flow_id': '6936eba1748ae09978ac0c04', 'particle_state_id': '6936eba1748ae09978ac0c02', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d482', 'result_id': '6936eba3494a6e38d021b326', 'flow_id': '6936eba3494a6e38d021b327', 'particle_state_id': '6936eba3494a6e38d021b325', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c9', 'result_id': '6936eba46a81281d3a277c77', 'flow_id': '6936eba46a81281d3a277c78', 'particle_state_id': '6936eba46a81281d3a277c76', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c86c', 'result_id': '6936eba4c9896b2b194a866e', 'flow_id': '6936eba4c9896b2b194a866f', 'particle_state_id': '6936eba4c9896b2b194a866d', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5e', 'result_id': '6936eba55a6158019055c77d', 'flow_id': '6936eba55a6158019055c77e', 'particle_state_id': '6936eba55a6158019055c77c', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d484', 'result_id': '6936eba53c1fa026c95e12a5', 'flow_id': '6936eba53c1fa026c95e12a6', 'particle_state_id': '6936eba53c1fa026c95e12a4', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cb', 'result_id': '6936eba79e3b6d74b14801fa', 'flow_id': '6936eba79e3b6d74b14801fb', 'particle_state_id': '6936eba79e3b6d74b14801f9', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c86e', 'result_id': '6936eba7349471dcd59e8140', 'flow_id': '6936eba7349471dcd59e8141', 'particle_state_id': '6936eba7349471dcd59e813f', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce60', 'result_id': '6936eba9748ae09978ac0c06', 'flow_id': '6936ebaa748ae09978ac0c07', 'particle_state_id': '6936eba9748ae09978ac0c05', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d486', 'result_id': '6936ebac494a6e38d021b329', 'flow_id': '6936ebac494a6e38d021b32a', 'particle_state_id': '6936ebac494a6e38d021b328', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cd', 'result_id': '6936ebad6a81281d3a277c7a', 'flow_id': '6936ebad6a81281d3a277c7b', 'particle_state_id': '6936ebad6a81281d3a277c79', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c870', 'result_id': '6936ebaec9896b2b194a8671', 'flow_id': '6936ebaec9896b2b194a8672', 'particle_state_id': '6936ebaec9896b2b194a8670', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce62', 'result_id': '6936ebae5a6158019055c780', 'flow_id': '6936ebae5a6158019055c781', 'particle_state_id': '6936ebae5a6158019055c77f', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d488', 'result_id': '6936ebae3c1fa026c95e12a8', 'flow_id': '6936ebae3c1fa026c95e12a9', 'particle_state_id': '6936ebae3c1fa026c95e12a7', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cf', 'result_id': '6936ebb09e3b6d74b14801fd', 'flow_id': '6936ebb09e3b6d74b14801fe', 'particle_state_id': '6936ebb09e3b6d74b14801fc', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c872', 'result_id': '6936ebaf349471dcd59e8143', 'flow_id': '6936ebaf349471dcd59e8144', 'particle_state_id': '6936ebaf349471dcd59e8142', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce64', 'result_id': '6936ebb1748ae09978ac0c09', 'flow_id': '6936ebb1748ae09978ac0c0a', 'particle_state_id': '6936ebb1748ae09978ac0c08', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c874', 'result_id': '6936ebb5494a6e38d021b32c', 'flow_id': '6936ebb5494a6e38d021b32d', 'particle_state_id': '6936ebb4494a6e38d021b32b', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48a', 'result_id': '6936ebb56a81281d3a277c7d', 'flow_id': '6936ebb56a81281d3a277c7e', 'particle_state_id': '6936ebb56a81281d3a277c7c', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d1', 'result_id': '6936ebafc9896b2b194a8674', 'flow_id': '6936ebafc9896b2b194a8675', 'particle_state_id': '6936ebaec9896b2b194a8673', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce66', 'result_id': '6936ebb65a6158019055c783', 'flow_id': '6936ebb65a6158019055c784', 'particle_state_id': '6936ebb65a6158019055c782', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48c', 'result_id': '6936ebb73c1fa026c95e12ab', 'flow_id': '6936ebb73c1fa026c95e12ac', 'particle_state_id': '6936ebb73c1fa026c95e12aa', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d3', 'result_id': '6936ebb7c9896b2b194a8677', 'flow_id': '6936ebb7c9896b2b194a8678', 'particle_state_id': '6936ebb6c9896b2b194a8676', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c876', 'result_id': '6936ebb9349471dcd59e8146', 'flow_id': '6936ebb9349471dcd59e8147', 'particle_state_id': '6936ebb8349471dcd59e8145', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce68', 'result_id': '6936ebb99e3b6d74b1480200', 'flow_id': '6936ebb99e3b6d74b1480201', 'particle_state_id': '6936ebb99e3b6d74b14801ff', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c878', 'result_id': '6936ebba748ae09978ac0c0c', 'flow_id': '6936ebba748ae09978ac0c0d', 'particle_state_id': '6936ebba748ae09978ac0c0b', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d5', 'result_id': '6936ebbd494a6e38d021b32f', 'flow_id': '6936ebbd494a6e38d021b330', 'particle_state_id': '6936ebbc494a6e38d021b32e', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48e', 'result_id': '6936ebbe6a81281d3a277c80', 'flow_id': '6936ebbe6a81281d3a277c81', 'particle_state_id': '6936ebbe6a81281d3a277c7f', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce6a', 'result_id': '6936ebbf5a6158019055c786', 'flow_id': '6936ebbf5a6158019055c787', 'particle_state_id': '6936ebbf5a6158019055c785', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d490', 'result_id': '6936ebbfc9896b2b194a867a', 'flow_id': '6936ebbfc9896b2b194a867b', 'particle_state_id': '6936ebbfc9896b2b194a8679', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d7', 'result_id': '6936ebbf3c1fa026c95e12ae', 'flow_id': '6936ebbf3c1fa026c95e12af', 'particle_state_id': '6936ebbf3c1fa026c95e12ad', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c87a', 'result_id': '6936ebc2349471dcd59e8149', 'flow_id': '6936ebc3349471dcd59e814a', 'particle_state_id': '6936ebc2349471dcd59e8148', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce6c', 'result_id': '6936ebc29e3b6d74b1480203', 'flow_id': '6936ebc39e3b6d74b1480204', 'particle_state_id': '6936ebc19e3b6d74b1480202', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c87c', 'result_id': '6936ebc2748ae09978ac0c0f', 'flow_id': '6936ebc3748ae09978ac0c10', 'particle_state_id': '6936ebc2748ae09978ac0c0e', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d492', 'result_id': '6936ebc5494a6e38d021b332', 'flow_id': '6936ebc5494a6e38d021b333', 'particle_state_id': '6936ebc5494a6e38d021b331', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7d9', 'result_id': '6936ebc56a81281d3a277c83', 'flow_id': '6936ebc66a81281d3a277c84', 'particle_state_id': '6936ebc56a81281d3a277c82', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce6e', 'result_id': '6936ebc7c9896b2b194a867d', 'flow_id': '6936ebc7c9896b2b194a867e', 'particle_state_id': '6936ebc7c9896b2b194a867c', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c87e', 'result_id': '6936ebc73c1fa026c95e12b1', 'flow_id': '6936ebc73c1fa026c95e12b2', 'particle_state_id': '6936ebc73c1fa026c95e12b0', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce70', 'result_id': '6936ebc75a6158019055c789', 'flow_id': '6936ebc75a6158019055c78a', 'particle_state_id': '6936ebc75a6158019055c788', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7db', 'result_id': '6936ebcb748ae09978ac0c12', 'flow_id': '6936ebcb748ae09978ac0c13', 'particle_state_id': '6936ebcb748ae09978ac0c11', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d494', 'result_id': '6936ebcc349471dcd59e814c', 'flow_id': '6936ebcc349471dcd59e814d', 'particle_state_id': '6936ebcc349471dcd59e814b', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7dd', 'result_id': '6936ebcc9e3b6d74b1480206', 'flow_id': '6936ebcc9e3b6d74b1480207', 'particle_state_id': '6936ebcc9e3b6d74b1480205', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c880', 'result_id': '6936ebce494a6e38d021b335', 'flow_id': '6936ebce494a6e38d021b336', 'particle_state_id': '6936ebce494a6e38d021b334', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d496', 'result_id': '6936ebcf6a81281d3a277c86', 'flow_id': '6936ebcf6a81281d3a277c87', 'particle_state_id': '6936ebcf6a81281d3a277c85', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce72', 'result_id': '6936ebd1c9896b2b194a8680', 'flow_id': '6936ebd1c9896b2b194a8681', 'particle_state_id': '6936ebd1c9896b2b194a867f', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d498', 'result_id': '6936ebd13c1fa026c95e12b4', 'flow_id': '6936ebd13c1fa026c95e12b5', 'particle_state_id': '6936ebd13c1fa026c95e12b3', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce74', 'result_id': '6936ebd15a6158019055c78c', 'flow_id': '6936ebd25a6158019055c78d', 'particle_state_id': '6936ebd15a6158019055c78b', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c882', 'result_id': '6936ebd3748ae09978ac0c15', 'flow_id': '6936ebd3748ae09978ac0c16', 'particle_state_id': '6936ebd3748ae09978ac0c14', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7df', 'result_id': '6936ebd49e3b6d74b1480209', 'flow_id': '6936ebd49e3b6d74b148020a', 'particle_state_id': '6936ebd49e3b6d74b1480208', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c884', 'result_id': '6936ebd4349471dcd59e814f', 'flow_id': '6936ebd4349471dcd59e8150', 'particle_state_id': '6936ebd4349471dcd59e814e', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce76', 'result_id': '6936ebd2494a6e38d021b338', 'flow_id': '6936ebd2494a6e38d021b339', 'particle_state_id': '6936ebd2494a6e38d021b337', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7e1', 'result_id': '6936ebd86a81281d3a277c89', 'flow_id': '6936ebd86a81281d3a277c8a', 'particle_state_id': '6936ebd86a81281d3a277c88', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49a', 'result_id': '6936ebdac9896b2b194a8683', 'flow_id': '6936ebdac9896b2b194a8684', 'particle_state_id': '6936ebdac9896b2b194a8682', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c886', 'result_id': '6936ebdb3c1fa026c95e12b7', 'flow_id': '6936ebdb3c1fa026c95e12b8', 'particle_state_id': '6936ebdb3c1fa026c95e12b6', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49c', 'result_id': '6936ebdb5a6158019055c78f', 'flow_id': '6936ebdb5a6158019055c790', 'particle_state_id': '6936ebdb5a6158019055c78e', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7e3', 'result_id': '6936ebdc494a6e38d021b33b', 'flow_id': '6936ebdc494a6e38d021b33c', 'particle_state_id': '6936ebdc494a6e38d021b33a', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce78', 'result_id': '6936ebdd748ae09978ac0c18', 'flow_id': '6936ebdd748ae09978ac0c19', 'particle_state_id': '6936ebdd748ae09978ac0c17', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e5', 'result_id': '6936ebdd349471dcd59e8152', 'flow_id': '6936ebdd349471dcd59e8153', 'particle_state_id': '6936ebdc349471dcd59e8151', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49e', 'result_id': '6936ebdc9e3b6d74b148020c', 'flow_id': '6936ebdc9e3b6d74b148020d', 'particle_state_id': '6936ebdc9e3b6d74b148020b', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c888', 'result_id': '6936ebe16a81281d3a277c8c', 'flow_id': '6936ebe16a81281d3a277c8d', 'particle_state_id': '6936ebe16a81281d3a277c8b', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7a', 'result_id': '6936ebe2c9896b2b194a8686', 'flow_id': '6936ebe2c9896b2b194a8687', 'particle_state_id': '6936ebe2c9896b2b194a8685', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a0', 'result_id': '6936ebe43c1fa026c95e12ba', 'flow_id': '6936ebe43c1fa026c95e12bb', 'particle_state_id': '6936ebe43c1fa026c95e12b9', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e7', 'result_id': '6936ebe45a6158019055c792', 'flow_id': '6936ebe45a6158019055c793', 'particle_state_id': '6936ebe45a6158019055c791', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88a', 'result_id': '6936ebe4494a6e38d021b33e', 'flow_id': '6936ebe4494a6e38d021b33f', 'particle_state_id': '6936ebe3494a6e38d021b33d', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7c', 'result_id': '6936ebe59e3b6d74b148020f', 'flow_id': '6936ebe59e3b6d74b1480210', 'particle_state_id': '6936ebe59e3b6d74b148020e', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a2', 'result_id': '6936ebe5349471dcd59e8155', 'flow_id': '6936ebe5349471dcd59e8156', 'particle_state_id': '6936ebe5349471dcd59e8154', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e9', 'result_id': '6936ebe7748ae09978ac0c1b', 'flow_id': '6936ebe7748ae09978ac0c1c', 'particle_state_id': '6936ebe7748ae09978ac0c1a', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88c', 'result_id': '6936ebea6a81281d3a277c8f', 'flow_id': '6936ebea6a81281d3a277c90', 'particle_state_id': '6936ebea6a81281d3a277c8e', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7e', 'result_id': '6936ebebc9896b2b194a8689', 'flow_id': '6936ebecc9896b2b194a868a', 'particle_state_id': '6936ebebc9896b2b194a8688', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a4', 'result_id': '6936ebec494a6e38d021b341', 'flow_id': '6936ebec494a6e38d021b342', 'particle_state_id': '6936ebec494a6e38d021b340', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7eb', 'result_id': '6936ebec5a6158019055c795', 'flow_id': '6936ebec5a6158019055c796', 'particle_state_id': '6936ebec5a6158019055c794', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88e', 'result_id': '6936ebed3c1fa026c95e12bd', 'flow_id': '6936ebee3c1fa026c95e12be', 'particle_state_id': '6936ebed3c1fa026c95e12bc', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce80', 'result_id': '6936ebee349471dcd59e8158', 'flow_id': '6936ebee349471dcd59e8159', 'particle_state_id': '6936ebed349471dcd59e8157', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a6', 'result_id': '6936ebed9e3b6d74b1480212', 'flow_id': '6936ebed9e3b6d74b1480213', 'particle_state_id': '6936ebed9e3b6d74b1480211', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7ed', 'result_id': '6936ebf0748ae09978ac0c1e', 'flow_id': '6936ebf0748ae09978ac0c1f', 'particle_state_id': '6936ebf0748ae09978ac0c1d', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c890', 'result_id': '6936ebf16a81281d3a277c92', 'flow_id': '6936ebf16a81281d3a277c93', 'particle_state_id': '6936ebf16a81281d3a277c91', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce82', 'result_id': '6936ebecc9896b2b194a868c', 'flow_id': '6936ebedc9896b2b194a868d', 'particle_state_id': '6936ebecc9896b2b194a868b', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a8', 'result_id': '6936ebf0494a6e38d021b344', 'flow_id': '6936ebf0494a6e38d021b345', 'particle_state_id': '6936ebf0494a6e38d021b343', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7ef', 'result_id': '6936ebf25a6158019055c798', 'flow_id': '6936ebf25a6158019055c799', 'particle_state_id': '6936ebf25a6158019055c797', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c892', 'result_id': '6936ebf1c9896b2b194a868f', 'flow_id': '6936ebf1c9896b2b194a8690', 'particle_state_id': '6936ebf1c9896b2b194a868e', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce84', 'result_id': '6936ebf29e3b6d74b1480215', 'flow_id': '6936ebf29e3b6d74b1480216', 'particle_state_id': '6936ebf29e3b6d74b1480214', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4aa', 'result_id': '6936ebf2349471dcd59e815b', 'flow_id': '6936ebf2349471dcd59e815c', 'particle_state_id': '6936ebf2349471dcd59e815a', 'status': 'success'}]}

## Estimate Flows

In [53]:
res = requests.post("http://localhost:8007/init_flow_estimation_collection")
print(res.json())

{'status': 'success', 'message': 'All 100 particle state records have been deleted.'}

In [54]:
rate_constant_lookup = {
    item['model_id']: item['rate_constant_id']
    for item in generate_rate_constant_res.json().get('results', [])
}
combined_list = []
for ss_item in solve_steady_state_res.json().get('results', []):
    model_id = ss_item.get('model_id')

    # Check if a matching rate_constant_id exists for this model_id
    if model_id in rate_constant_lookup:
        # Create the combined dictionary
        combined_dict = {
            'model_id': model_id,
            'rate_constant_id': rate_constant_lookup[model_id],
            'particle_state_id': ss_item.get('particle_state_id'),
            'flow_id': ss_item.get('flow_id')
        }
        combined_list.append(combined_dict)

In [55]:
flow_estimation_res = requests.post(
    "http://localhost:8007/estimate_flow/batch",
    json = {
        "items": combined_list,
    }
)
if flow_estimation_res.ok:
    print("Response:", flow_estimation_res.json())
else:
    print("Error:", flow_estimation_res.status_code, flow_estimation_res.text)

Response: {'total': 100, 'successful': 100, 'failed': 0, 'results': [{'model_id': '6936eb6c35547f4955bed7bf', 'flow_estimation_id': '6936ebf5dff20d37d4c47077', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47a', 'flow_estimation_id': '6936ebf562b5323f506399b3', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c1', 'flow_estimation_id': '6936ebf598d0367516d761ac', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c864', 'flow_estimation_id': '6936ebf521553a9694201110', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce54', 'flow_estimation_id': '6936ebf598d0367516d761ad', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c3', 'flow_estimation_id': '6936ebf521553a9694201111', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c862', 'flow_estimation_id': '6936ebf562b5323f506399b4', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47c', 'flow_estimation_id': '6936ebf5dff20d37d4c47078', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce56', 'flow_estimation_id': '6936ebf698d0367516d761ae', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce58', 'flow_estimation_id': '6936ebf621553a9694201112', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47e', 'flow_estimation_id': '6936ebf662b5323f506399b5', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c5', 'flow_estimation_id': '6936ebf6dff20d37d4c47079', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5a', 'flow_estimation_id': '6936ebf698d0367516d761af', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c866', 'flow_estimation_id': '6936ebf621553a9694201113', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c7', 'flow_estimation_id': '6936ebf662b5323f506399b6', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d480', 'flow_estimation_id': '6936ebf6dff20d37d4c4707a', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c868', 'flow_estimation_id': '6936ebf698d0367516d761b0', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c86a', 'flow_estimation_id': '6936ebf621553a9694201114', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5c', 'flow_estimation_id': '6936ebf662b5323f506399b7', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d482', 'flow_estimation_id': '6936ebf6dff20d37d4c4707b', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c9', 'flow_estimation_id': '6936ebf698d0367516d761b1', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c86c', 'flow_estimation_id': '6936ebf621553a9694201115', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5e', 'flow_estimation_id': '6936ebf662b5323f506399b8', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d484', 'flow_estimation_id': '6936ebf6dff20d37d4c4707c', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cb', 'flow_estimation_id': '6936ebf698d0367516d761b2', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c86e', 'flow_estimation_id': '6936ebf621553a9694201116', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce60', 'flow_estimation_id': '6936ebf662b5323f506399b9', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d486', 'flow_estimation_id': '6936ebf6dff20d37d4c4707d', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cd', 'flow_estimation_id': '6936ebf698d0367516d761b3', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c870', 'flow_estimation_id': '6936ebf621553a9694201117', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce62', 'flow_estimation_id': '6936ebf662b5323f506399ba', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d488', 'flow_estimation_id': '6936ebf6dff20d37d4c4707e', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cf', 'flow_estimation_id': '6936ebf698d0367516d761b4', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c872', 'flow_estimation_id': '6936ebf621553a9694201118', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce64', 'flow_estimation_id': '6936ebf662b5323f506399bb', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c874', 'flow_estimation_id': '6936ebf6dff20d37d4c4707f', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48a', 'flow_estimation_id': '6936ebf798d0367516d761b5', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d1', 'flow_estimation_id': '6936ebf762b5323f506399bc', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce66', 'flow_estimation_id': '6936ebf721553a9694201119', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48c', 'flow_estimation_id': '6936ebf7dff20d37d4c47080', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d3', 'flow_estimation_id': '6936ebf798d0367516d761b6', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c876', 'flow_estimation_id': '6936ebf762b5323f506399bd', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce68', 'flow_estimation_id': '6936ebf721553a969420111a', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c878', 'flow_estimation_id': '6936ebf7dff20d37d4c47081', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d5', 'flow_estimation_id': '6936ebf798d0367516d761b7', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48e', 'flow_estimation_id': '6936ebf762b5323f506399be', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce6a', 'flow_estimation_id': '6936ebf721553a969420111b', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d490', 'flow_estimation_id': '6936ebf7dff20d37d4c47082', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d7', 'flow_estimation_id': '6936ebf798d0367516d761b8', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c87a', 'flow_estimation_id': '6936ebf762b5323f506399bf', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce6c', 'flow_estimation_id': '6936ebf721553a969420111c', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c87c', 'flow_estimation_id': '6936ebf7dff20d37d4c47083', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d492', 'flow_estimation_id': '6936ebf798d0367516d761b9', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7d9', 'flow_estimation_id': '6936ebf762b5323f506399c0', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce6e', 'flow_estimation_id': '6936ebf7dff20d37d4c47084', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c87e', 'flow_estimation_id': '6936ebf721553a969420111d', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce70', 'flow_estimation_id': '6936ebf798d0367516d761ba', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7db', 'flow_estimation_id': '6936ebf762b5323f506399c1', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d494', 'flow_estimation_id': '6936ebf7dff20d37d4c47085', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7dd', 'flow_estimation_id': '6936ebf721553a969420111e', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c880', 'flow_estimation_id': '6936ebf798d0367516d761bb', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d496', 'flow_estimation_id': '6936ebf862b5323f506399c2', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce72', 'flow_estimation_id': '6936ebf8dff20d37d4c47086', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d498', 'flow_estimation_id': '6936ebf821553a969420111f', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce74', 'flow_estimation_id': '6936ebf898d0367516d761bc', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c882', 'flow_estimation_id': '6936ebf821553a9694201120', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7df', 'flow_estimation_id': '6936ebf8dff20d37d4c47087', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c884', 'flow_estimation_id': '6936ebf862b5323f506399c3', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce76', 'flow_estimation_id': '6936ebf898d0367516d761bd', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7e1', 'flow_estimation_id': '6936ebf821553a9694201121', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49a', 'flow_estimation_id': '6936ebf8dff20d37d4c47088', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c886', 'flow_estimation_id': '6936ebf862b5323f506399c4', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49c', 'flow_estimation_id': '6936ebf898d0367516d761be', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7e3', 'flow_estimation_id': '6936ebf821553a9694201122', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce78', 'flow_estimation_id': '6936ebf862b5323f506399c5', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e5', 'flow_estimation_id': '6936ebf8dff20d37d4c47089', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49e', 'flow_estimation_id': '6936ebf898d0367516d761bf', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c888', 'flow_estimation_id': '6936ebf821553a9694201123', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7a', 'flow_estimation_id': '6936ebf862b5323f506399c6', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a0', 'flow_estimation_id': '6936ebf8dff20d37d4c4708a', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e7', 'flow_estimation_id': '6936ebf898d0367516d761c0', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88a', 'flow_estimation_id': '6936ebf821553a9694201124', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7c', 'flow_estimation_id': '6936ebf862b5323f506399c7', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a2', 'flow_estimation_id': '6936ebf8dff20d37d4c4708b', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e9', 'flow_estimation_id': '6936ebf898d0367516d761c1', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88c', 'flow_estimation_id': '6936ebf821553a9694201125', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7e', 'flow_estimation_id': '6936ebf862b5323f506399c8', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a4', 'flow_estimation_id': '6936ebf8dff20d37d4c4708c', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7eb', 'flow_estimation_id': '6936ebf998d0367516d761c2', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88e', 'flow_estimation_id': '6936ebf962b5323f506399c9', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce80', 'flow_estimation_id': '6936ebf921553a9694201126', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a6', 'flow_estimation_id': '6936ebf9dff20d37d4c4708d', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7ed', 'flow_estimation_id': '6936ebf998d0367516d761c3', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c890', 'flow_estimation_id': '6936ebf921553a9694201127', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce82', 'flow_estimation_id': '6936ebf962b5323f506399ca', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a8', 'flow_estimation_id': '6936ebf9dff20d37d4c4708e', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7ef', 'flow_estimation_id': '6936ebf998d0367516d761c4', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c892', 'flow_estimation_id': '6936ebf921553a9694201128', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce84', 'flow_estimation_id': '6936ebf962b5323f506399cb', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4aa', 'flow_estimation_id': '6936ebf9dff20d37d4c4708f', 'status': 'success'}]}

## Result processing

In [56]:
res = requests.post("http://localhost:8008/init_processed_result_collection")
print(res.json())

{'status': 'success', 'message': 'All 100 processed result records have been deleted.'}

In [57]:
interaction_matrix_data = interaction_matrix_res.json()
steady_state_data = solve_steady_state_res.json()
flow_estimation_data = flow_estimation_res.json()

# Map 1: model_id -> interaction_matrix_id
interaction_matrix_lookup = {
    item['model_id']: item['interaction_matrix_id']
    for item in interaction_matrix_data.get('results', [])
}

# Map 2: model_id -> flow_estimation_id
flow_estimation_lookup = {
    item['model_id']: item['flow_estimation_id']
    for item in flow_estimation_data.get('results', [])
}

process_result_endpoint_inputs = []

for ss_item in steady_state_data.get('results', []):
    model_id = ss_item.get('model_id')

    # Check if this model_id exists in BOTH lookup maps
    if model_id in interaction_matrix_lookup and model_id in flow_estimation_lookup:
        
        # Build the final dictionary
        combined_input = {
            'model_id': model_id,
            'result_id': ss_item.get('result_id'),
            'particle_state_id': ss_item.get('particle_state_id'),
            # Retrieve IDs from the lookup maps
            'interaction_matrix_id': interaction_matrix_lookup[model_id],
            'flow_estimation_id': flow_estimation_lookup[model_id]
        }
        
        process_result_endpoint_inputs.append(combined_input)

In [58]:
rate_constant_data = generate_rate_constant_res.json()

# 1. Create a lookup map for the Rate Constant IDs
rate_constant_lookup = {
    item['model_id']: item['rate_constant_id']
    for item in rate_constant_data.get('results', [])
}

# 2. Iterate over the Rate Constant lookup and combine with the Interaction Matrix lookup
interaction_matrix_dict_endpoint_inputs = []

for item in rate_constant_data.get('results', []):
    model_id = item.get('model_id')
    rate_constant_id = item.get('rate_constant_id')

    # Check if this model_id exists in the Interaction Matrix lookup
    if model_id in interaction_matrix_lookup:
        
        combined_input = {
            'model_id': model_id,
            'rate_constant_id': rate_constant_id,
            # Retrieve the ID from the existing lookup map
            'interaction_matrix_id': interaction_matrix_lookup[model_id]
        }
        
        interaction_matrix_dict_endpoint_inputs.append(combined_input)

In [59]:
interaction_matrix_dict_res = requests.post(
    "http://localhost:8005/generate_interaction_matrix_dict/batch", 
    json={
        "items":interaction_matrix_dict_endpoint_inputs
    }
)

if interaction_matrix_dict_res.ok:
    print("Response:", interaction_matrix_dict_res.json())
else:
    print("Error:", interaction_matrix_dict_res.status_code, interaction_matrix_dict_res.text)

Response: {'status': 'success', 'count': 100, 'successful': 100, 'failed': 0, 'results': [{'model_id': '6936eb6c35547f4955bed7c1', 'interaction_matrix_id': '6936eb74e3e8bfa0c63913f9', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cfc480e63d6f0d47a', 'interaction_matrix_id': '6936eb74e3e8bfa0c63913f8', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cb19f000d48b1c864', 'interaction_matrix_id': '6936eb74e3e8bfa0c63913fa', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6c35547f4955bed7bf', 'interaction_matrix_id': '6936eb74e3e8bfa0c63913f7', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cc77c0ff1798fce54', 'interaction_matrix_id': '6936eb75e3e8bfa0c63913fb', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6c35547f4955bed7c3', 'interaction_matrix_id': '6936eb75e3e8bfa0c63913fc', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cb19f000d48b1c862', 'interaction_matrix_id': '6936eb75e3e8bfa0c63913fd', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cfc480e63d6f0d47c', 'interaction_matrix_id': '6936eb75e3e8bfa0c63913fe', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cc77c0ff1798fce56', 'interaction_matrix_id': '6936eb76e3e8bfa0c63913ff', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cc77c0ff1798fce58', 'interaction_matrix_id': '6936eb76e3e8bfa0c6391400', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cfc480e63d6f0d47e', 'interaction_matrix_id': '6936eb76e3e8bfa0c6391401', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6c35547f4955bed7c5', 'interaction_matrix_id': '6936eb76e3e8bfa0c6391402', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cc77c0ff1798fce5a', 'interaction_matrix_id': '6936eb77e3e8bfa0c6391403', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cb19f000d48b1c866', 'interaction_matrix_id': '6936eb77e3e8bfa0c6391404', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cfc480e63d6f0d480', 'interaction_matrix_id': '6936eb77e3e8bfa0c6391406', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6c35547f4955bed7c7', 'interaction_matrix_id': '6936eb77e3e8bfa0c6391405', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cb19f000d48b1c868', 'interaction_matrix_id': '6936eb78e3e8bfa0c6391407', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cb19f000d48b1c86a', 'interaction_matrix_id': '6936eb78e3e8bfa0c6391408', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cc77c0ff1798fce5c', 'interaction_matrix_id': '6936eb78e3e8bfa0c6391409', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cfc480e63d6f0d482', 'interaction_matrix_id': '6936eb78e3e8bfa0c639140a', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6c35547f4955bed7c9', 'interaction_matrix_id': '6936eb78e3e8bfa0c639140b', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cb19f000d48b1c86c', 'interaction_matrix_id': '6936eb78e3e8bfa0c639140c', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cc77c0ff1798fce5e', 'interaction_matrix_id': '6936eb78e3e8bfa0c639140d', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6cfc480e63d6f0d484', 'interaction_matrix_id': '6936eb78e3e8bfa0c639140e', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6db19f000d48b1c86e', 'interaction_matrix_id': '6936eb79e3e8bfa0c6391410', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6d35547f4955bed7cb', 'interaction_matrix_id': '6936eb79e3e8bfa0c639140f', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dc77c0ff1798fce60', 'interaction_matrix_id': '6936eb79e3e8bfa0c6391411', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dfc480e63d6f0d486', 'interaction_matrix_id': '6936eb79e3e8bfa0c6391412', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6d35547f4955bed7cd', 'interaction_matrix_id': '6936eb7ae3e8bfa0c6391413', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6db19f000d48b1c870', 'interaction_matrix_id': '6936eb7ae3e8bfa0c6391414', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dc77c0ff1798fce62', 'interaction_matrix_id': '6936eb7ae3e8bfa0c6391415', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dfc480e63d6f0d488', 'interaction_matrix_id': '6936eb7ae3e8bfa0c6391416', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6d35547f4955bed7cf', 'interaction_matrix_id': '6936eb7be3e8bfa0c6391417', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6db19f000d48b1c872', 'interaction_matrix_id': '6936eb7be3e8bfa0c6391418', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dc77c0ff1798fce64', 'interaction_matrix_id': '6936eb7be3e8bfa0c6391419', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6db19f000d48b1c874', 'interaction_matrix_id': '6936eb7be3e8bfa0c639141a', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dfc480e63d6f0d48a', 'interaction_matrix_id': '6936eb7ce3e8bfa0c639141b', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6d35547f4955bed7d1', 'interaction_matrix_id': '6936eb7ce3e8bfa0c639141c', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dc77c0ff1798fce66', 'interaction_matrix_id': '6936eb7ce3e8bfa0c639141d', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dfc480e63d6f0d48c', 'interaction_matrix_id': '6936eb7ce3e8bfa0c639141e', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6d35547f4955bed7d3', 'interaction_matrix_id': '6936eb7ce3e8bfa0c639141f', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6db19f000d48b1c876', 'interaction_matrix_id': '6936eb7ce3e8bfa0c6391420', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dc77c0ff1798fce68', 'interaction_matrix_id': '6936eb7ce3e8bfa0c6391421', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6db19f000d48b1c878', 'interaction_matrix_id': '6936eb7ce3e8bfa0c6391422', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6d35547f4955bed7d5', 'interaction_matrix_id': '6936eb7de3e8bfa0c6391423', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dfc480e63d6f0d48e', 'interaction_matrix_id': '6936eb7de3e8bfa0c6391424', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dc77c0ff1798fce6a', 'interaction_matrix_id': '6936eb7de3e8bfa0c6391425', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dfc480e63d6f0d490', 'interaction_matrix_id': '6936eb7de3e8bfa0c6391426', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6d35547f4955bed7d7', 'interaction_matrix_id': '6936eb7ee3e8bfa0c6391427', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6db19f000d48b1c87a', 'interaction_matrix_id': '6936eb7ee3e8bfa0c6391428', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6dc77c0ff1798fce6c', 'interaction_matrix_id': '6936eb7ee3e8bfa0c6391429', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6eb19f000d48b1c87c', 'interaction_matrix_id': '6936eb7ee3e8bfa0c639142a', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6efc480e63d6f0d492', 'interaction_matrix_id': '6936eb7fe3e8bfa0c639142b', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6e35547f4955bed7d9', 'interaction_matrix_id': '6936eb7fe3e8bfa0c639142c', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ec77c0ff1798fce6e', 'interaction_matrix_id': '6936eb7fe3e8bfa0c639142d', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6eb19f000d48b1c87e', 'interaction_matrix_id': '6936eb7fe3e8bfa0c639142e', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ec77c0ff1798fce70', 'interaction_matrix_id': '6936eb80e3e8bfa0c639142f', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6e35547f4955bed7db', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391430', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6efc480e63d6f0d494', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391431', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6e35547f4955bed7dd', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391432', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6eb19f000d48b1c880', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391433', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6efc480e63d6f0d496', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391434', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ec77c0ff1798fce72', 'interaction_matrix_id': '6936eb80e3e8bfa0c6391435', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6efc480e63d6f0d498', 'interaction_matrix_id': '6936eb81e3e8bfa0c6391436', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ec77c0ff1798fce74', 'interaction_matrix_id': '6936eb81e3e8bfa0c6391437', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6eb19f000d48b1c882', 'interaction_matrix_id': '6936eb81e3e8bfa0c6391438', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6e35547f4955bed7df', 'interaction_matrix_id': '6936eb81e3e8bfa0c6391439', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6eb19f000d48b1c884', 'interaction_matrix_id': '6936eb81e3e8bfa0c639143a', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ec77c0ff1798fce76', 'interaction_matrix_id': '6936eb82e3e8bfa0c639143b', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6e35547f4955bed7e1', 'interaction_matrix_id': '6936eb82e3e8bfa0c639143c', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6efc480e63d6f0d49a', 'interaction_matrix_id': '6936eb82e3e8bfa0c639143d', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6eb19f000d48b1c886', 'interaction_matrix_id': '6936eb82e3e8bfa0c639143e', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6efc480e63d6f0d49c', 'interaction_matrix_id': '6936eb83e3e8bfa0c639143f', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6e35547f4955bed7e3', 'interaction_matrix_id': '6936eb83e3e8bfa0c6391440', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ec77c0ff1798fce78', 'interaction_matrix_id': '6936eb83e3e8bfa0c6391441', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6f35547f4955bed7e5', 'interaction_matrix_id': '6936eb83e3e8bfa0c6391442', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6efc480e63d6f0d49e', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391443', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fb19f000d48b1c888', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391444', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fc77c0ff1798fce7a', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391445', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ffc480e63d6f0d4a0', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391446', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6f35547f4955bed7e7', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391447', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fb19f000d48b1c88a', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391448', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fc77c0ff1798fce7c', 'interaction_matrix_id': '6936eb84e3e8bfa0c6391449', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ffc480e63d6f0d4a2', 'interaction_matrix_id': '6936eb85e3e8bfa0c639144a', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6f35547f4955bed7e9', 'interaction_matrix_id': '6936eb85e3e8bfa0c639144b', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fb19f000d48b1c88c', 'interaction_matrix_id': '6936eb85e3e8bfa0c639144c', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fc77c0ff1798fce7e', 'interaction_matrix_id': '6936eb85e3e8bfa0c639144d', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ffc480e63d6f0d4a4', 'interaction_matrix_id': '6936eb85e3e8bfa0c639144e', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6f35547f4955bed7eb', 'interaction_matrix_id': '6936eb86e3e8bfa0c639144f', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fb19f000d48b1c88e', 'interaction_matrix_id': '6936eb86e3e8bfa0c6391450', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fc77c0ff1798fce80', 'interaction_matrix_id': '6936eb86e3e8bfa0c6391451', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ffc480e63d6f0d4a6', 'interaction_matrix_id': '6936eb86e3e8bfa0c6391452', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6f35547f4955bed7ed', 'interaction_matrix_id': '6936eb87e3e8bfa0c6391453', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fb19f000d48b1c890', 'interaction_matrix_id': '6936eb87e3e8bfa0c6391454', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fc77c0ff1798fce82', 'interaction_matrix_id': '6936eb87e3e8bfa0c6391455', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ffc480e63d6f0d4a8', 'interaction_matrix_id': '6936eb87e3e8bfa0c6391456', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6f35547f4955bed7ef', 'interaction_matrix_id': '6936eb88e3e8bfa0c6391457', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fb19f000d48b1c892', 'interaction_matrix_id': '6936eb88e3e8bfa0c6391458', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6fc77c0ff1798fce84', 'interaction_matrix_id': '6936eb88e3e8bfa0c6391459', 'status': 'interaction matrix_dict generated (parallel)'}, {'model_id': '6936eb6ffc480e63d6f0d4aa', 'interaction_matrix_id': '6936eb88e3e8bfa0c639145a', 'status': 'interaction matrix_dict generated (parallel)'}]}

In [60]:
process_result_res = requests.post(
    "http://localhost:8008/process_result/batch",
    json = {
        "items":process_result_endpoint_inputs
    }
)
if process_result_res.ok:
    print("Response:", process_result_res.json())
else:
    print("Error:", process_result_res.status_code, process_result_res.text)

Response: {'status': 'success', 'count': 100, 'successful': 100, 'failed': 0, 'results': [{'model_id': '6936eb6c35547f4955bed7c1', 'processed_result_id': '6936ec12768ec624a89fe4b6', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47a', 'processed_result_id': '6936ec12e9c561e8680b95f4', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c864', 'processed_result_id': '6936ec12ed11bd1165b8b3af', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7bf', 'processed_result_id': '6936ec1263b20b32e203b0bd', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c3', 'processed_result_id': '6936ec13e9c561e8680b95f5', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce54', 'processed_result_id': '6936ec13768ec624a89fe4b7', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47c', 'processed_result_id': '6936ec1363b20b32e203b0be', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c862', 'processed_result_id': '6936ec13ed11bd1165b8b3b0', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce58', 'processed_result_id': '6936ec14768ec624a89fe4b8', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce56', 'processed_result_id': '6936ec14e9c561e8680b95f6', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47e', 'processed_result_id': '6936ec1463b20b32e203b0bf', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c5', 'processed_result_id': '6936ec14ed11bd1165b8b3b1', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5a', 'processed_result_id': '6936ec15768ec624a89fe4b9', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c866', 'processed_result_id': '6936ec15e9c561e8680b95f7', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c7', 'processed_result_id': '6936ec1563b20b32e203b0c0', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d480', 'processed_result_id': '6936ec15ed11bd1165b8b3b2', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c868', 'processed_result_id': '6936ec16768ec624a89fe4ba', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c86a', 'processed_result_id': '6936ec16e9c561e8680b95f8', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5c', 'processed_result_id': '6936ec1663b20b32e203b0c1', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d482', 'processed_result_id': '6936ec16ed11bd1165b8b3b3', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c9', 'processed_result_id': '6936ec17768ec624a89fe4bb', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5e', 'processed_result_id': '6936ec1763b20b32e203b0c2', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c86c', 'processed_result_id': '6936ec17e9c561e8680b95f9', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d484', 'processed_result_id': '6936ec17ed11bd1165b8b3b4', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cb', 'processed_result_id': '6936ec18768ec624a89fe4bc', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c86e', 'processed_result_id': '6936ec1863b20b32e203b0c3', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce60', 'processed_result_id': '6936ec18e9c561e8680b95fa', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d486', 'processed_result_id': '6936ec18ed11bd1165b8b3b5', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cd', 'processed_result_id': '6936ec19768ec624a89fe4bd', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c870', 'processed_result_id': '6936ec1963b20b32e203b0c4', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce62', 'processed_result_id': '6936ec19e9c561e8680b95fb', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d488', 'processed_result_id': '6936ec19ed11bd1165b8b3b6', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cf', 'processed_result_id': '6936ec19768ec624a89fe4be', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c872', 'processed_result_id': '6936ec1963b20b32e203b0c5', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce64', 'processed_result_id': '6936ec19e9c561e8680b95fc', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c874', 'processed_result_id': '6936ec1aed11bd1165b8b3b7', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48a', 'processed_result_id': '6936ec1a768ec624a89fe4bf', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce66', 'processed_result_id': '6936ec1ae9c561e8680b95fd', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d1', 'processed_result_id': '6936ec1a63b20b32e203b0c6', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48c', 'processed_result_id': '6936ec1aed11bd1165b8b3b8', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d3', 'processed_result_id': '6936ec1b768ec624a89fe4c0', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c876', 'processed_result_id': '6936ec1be9c561e8680b95fe', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce68', 'processed_result_id': '6936ec1b63b20b32e203b0c7', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c878', 'processed_result_id': '6936ec1bed11bd1165b8b3b9', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d5', 'processed_result_id': '6936ec1c768ec624a89fe4c1', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48e', 'processed_result_id': '6936ec1ce9c561e8680b95ff', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce6a', 'processed_result_id': '6936ec1c63b20b32e203b0c8', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d490', 'processed_result_id': '6936ec1ced11bd1165b8b3ba', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d7', 'processed_result_id': '6936ec1d768ec624a89fe4c2', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c87a', 'processed_result_id': '6936ec1de9c561e8680b9600', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce6c', 'processed_result_id': '6936ec1d63b20b32e203b0c9', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c87c', 'processed_result_id': '6936ec1ded11bd1165b8b3bb', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d492', 'processed_result_id': '6936ec1d768ec624a89fe4c3', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7d9', 'processed_result_id': '6936ec1de9c561e8680b9601', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce6e', 'processed_result_id': '6936ec1d63b20b32e203b0ca', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c87e', 'processed_result_id': '6936ec1eed11bd1165b8b3bc', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce70', 'processed_result_id': '6936ec1e768ec624a89fe4c4', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7db', 'processed_result_id': '6936ec1ee9c561e8680b9602', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d494', 'processed_result_id': '6936ec1e63b20b32e203b0cb', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7dd', 'processed_result_id': '6936ec1eed11bd1165b8b3bd', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c880', 'processed_result_id': '6936ec1f768ec624a89fe4c5', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d496', 'processed_result_id': '6936ec1fe9c561e8680b9603', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce72', 'processed_result_id': '6936ec1f63b20b32e203b0cc', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d498', 'processed_result_id': '6936ec1fed11bd1165b8b3be', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce74', 'processed_result_id': '6936ec20768ec624a89fe4c6', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c882', 'processed_result_id': '6936ec20e9c561e8680b9604', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7df', 'processed_result_id': '6936ec2063b20b32e203b0cd', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c884', 'processed_result_id': '6936ec20ed11bd1165b8b3bf', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce76', 'processed_result_id': '6936ec21768ec624a89fe4c7', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7e1', 'processed_result_id': '6936ec21e9c561e8680b9605', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49a', 'processed_result_id': '6936ec2163b20b32e203b0ce', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c886', 'processed_result_id': '6936ec21ed11bd1165b8b3c0', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49c', 'processed_result_id': '6936ec21768ec624a89fe4c8', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7e3', 'processed_result_id': '6936ec21e9c561e8680b9606', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce78', 'processed_result_id': '6936ec2163b20b32e203b0cf', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e5', 'processed_result_id': '6936ec22ed11bd1165b8b3c1', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49e', 'processed_result_id': '6936ec22768ec624a89fe4c9', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c888', 'processed_result_id': '6936ec22e9c561e8680b9607', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7a', 'processed_result_id': '6936ec2263b20b32e203b0d0', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a0', 'processed_result_id': '6936ec22ed11bd1165b8b3c2', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e7', 'processed_result_id': '6936ec23768ec624a89fe4ca', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88a', 'processed_result_id': '6936ec23e9c561e8680b9608', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7c', 'processed_result_id': '6936ec2363b20b32e203b0d1', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a2', 'processed_result_id': '6936ec23ed11bd1165b8b3c3', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e9', 'processed_result_id': '6936ec24768ec624a89fe4cb', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88c', 'processed_result_id': '6936ec24e9c561e8680b9609', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7e', 'processed_result_id': '6936ec2463b20b32e203b0d2', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a4', 'processed_result_id': '6936ec24ed11bd1165b8b3c4', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7eb', 'processed_result_id': '6936ec25768ec624a89fe4cc', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88e', 'processed_result_id': '6936ec25e9c561e8680b960a', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce80', 'processed_result_id': '6936ec2563b20b32e203b0d3', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a6', 'processed_result_id': '6936ec25ed11bd1165b8b3c5', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7ed', 'processed_result_id': '6936ec25768ec624a89fe4cd', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c890', 'processed_result_id': '6936ec26e9c561e8680b960b', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce82', 'processed_result_id': '6936ec2663b20b32e203b0d4', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a8', 'processed_result_id': '6936ec26ed11bd1165b8b3c6', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7ef', 'processed_result_id': '6936ec26768ec624a89fe4ce', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c892', 'processed_result_id': '6936ec26e9c561e8680b960c', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce84', 'processed_result_id': '6936ec2663b20b32e203b0d5', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4aa', 'processed_result_id': '6936ec27ed11bd1165b8b3c7', 'status': 'success'}]}

In [61]:
processed_result_data = process_result_res.json()
process_result_by_comp_inputs = []
for item in processed_result_data.get('results', []):
    model_id = item.get('model_id')
    processed_result_id = item.get('processed_result_id')

    # 2. Check if a matching flow_estimation_id exists for this model_id
    if model_id in flow_estimation_lookup:
        
        # 3. Build the final dictionary
        combined_input = {
            'model_id': model_id,
            'processed_result_id': processed_result_id,
            # Retrieve the ID from the existing lookup map
            'flow_estimation_id': flow_estimation_lookup[model_id]
        }
        
        process_result_by_comp_inputs.append(combined_input)

In [62]:
process_results_by_comp_res = requests.post("http://localhost:8008/extract_results_by_compartment/batch",
    json = {
        "items": process_result_by_comp_inputs
    })

In [63]:
if process_results_by_comp_res.ok:
    print("Response:", process_results_by_comp_res.json())
else:
    print("Error:", process_results_by_comp_res.status_code, process_results_by_comp_res.text)

Response: {'status': 'success', 'count': 100, 'successful': 100, 'failed': 0, 'results': [{'model_id': '6936eb6c35547f4955bed7c1', 'processed_result_id': '6936ec12768ec624a89fe4b6', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c864', 'processed_result_id': '6936ec12ed11bd1165b8b3af', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47a', 'processed_result_id': '6936ec12e9c561e8680b95f4', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7bf', 'processed_result_id': '6936ec1263b20b32e203b0bd', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47c', 'processed_result_id': '6936ec1363b20b32e203b0be', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce54', 'processed_result_id': '6936ec13768ec624a89fe4b7', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c3', 'processed_result_id': '6936ec13e9c561e8680b95f5', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c862', 'processed_result_id': '6936ec13ed11bd1165b8b3b0', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce58', 'processed_result_id': '6936ec14768ec624a89fe4b8', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce56', 'processed_result_id': '6936ec14e9c561e8680b95f6', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47e', 'processed_result_id': '6936ec1463b20b32e203b0bf', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c5', 'processed_result_id': '6936ec14ed11bd1165b8b3b1', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5a', 'processed_result_id': '6936ec15768ec624a89fe4b9', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c866', 'processed_result_id': '6936ec15e9c561e8680b95f7', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c7', 'processed_result_id': '6936ec1563b20b32e203b0c0', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d480', 'processed_result_id': '6936ec15ed11bd1165b8b3b2', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5c', 'processed_result_id': '6936ec1663b20b32e203b0c1', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c868', 'processed_result_id': '6936ec16768ec624a89fe4ba', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c86a', 'processed_result_id': '6936ec16e9c561e8680b95f8', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d482', 'processed_result_id': '6936ec16ed11bd1165b8b3b3', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5e', 'processed_result_id': '6936ec1763b20b32e203b0c2', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c9', 'processed_result_id': '6936ec17768ec624a89fe4bb', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d484', 'processed_result_id': '6936ec17ed11bd1165b8b3b4', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c86c', 'processed_result_id': '6936ec17e9c561e8680b95f9', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c86e', 'processed_result_id': '6936ec1863b20b32e203b0c3', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cb', 'processed_result_id': '6936ec18768ec624a89fe4bc', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce60', 'processed_result_id': '6936ec18e9c561e8680b95fa', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d486', 'processed_result_id': '6936ec18ed11bd1165b8b3b5', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cd', 'processed_result_id': '6936ec19768ec624a89fe4bd', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c870', 'processed_result_id': '6936ec1963b20b32e203b0c4', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d488', 'processed_result_id': '6936ec19ed11bd1165b8b3b6', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce62', 'processed_result_id': '6936ec19e9c561e8680b95fb', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cf', 'processed_result_id': '6936ec19768ec624a89fe4be', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce64', 'processed_result_id': '6936ec19e9c561e8680b95fc', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c872', 'processed_result_id': '6936ec1963b20b32e203b0c5', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c874', 'processed_result_id': '6936ec1aed11bd1165b8b3b7', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48a', 'processed_result_id': '6936ec1a768ec624a89fe4bf', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d1', 'processed_result_id': '6936ec1a63b20b32e203b0c6', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce66', 'processed_result_id': '6936ec1ae9c561e8680b95fd', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48c', 'processed_result_id': '6936ec1aed11bd1165b8b3b8', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d3', 'processed_result_id': '6936ec1b768ec624a89fe4c0', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c876', 'processed_result_id': '6936ec1be9c561e8680b95fe', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce68', 'processed_result_id': '6936ec1b63b20b32e203b0c7', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c878', 'processed_result_id': '6936ec1bed11bd1165b8b3b9', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d5', 'processed_result_id': '6936ec1c768ec624a89fe4c1', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48e', 'processed_result_id': '6936ec1ce9c561e8680b95ff', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce6a', 'processed_result_id': '6936ec1c63b20b32e203b0c8', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d490', 'processed_result_id': '6936ec1ced11bd1165b8b3ba', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce6c', 'processed_result_id': '6936ec1d63b20b32e203b0c9', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d7', 'processed_result_id': '6936ec1d768ec624a89fe4c2', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c87a', 'processed_result_id': '6936ec1de9c561e8680b9600', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c87c', 'processed_result_id': '6936ec1ded11bd1165b8b3bb', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d492', 'processed_result_id': '6936ec1d768ec624a89fe4c3', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7d9', 'processed_result_id': '6936ec1de9c561e8680b9601', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce6e', 'processed_result_id': '6936ec1d63b20b32e203b0ca', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c87e', 'processed_result_id': '6936ec1eed11bd1165b8b3bc', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce70', 'processed_result_id': '6936ec1e768ec624a89fe4c4', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7db', 'processed_result_id': '6936ec1ee9c561e8680b9602', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d494', 'processed_result_id': '6936ec1e63b20b32e203b0cb', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7dd', 'processed_result_id': '6936ec1eed11bd1165b8b3bd', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d496', 'processed_result_id': '6936ec1fe9c561e8680b9603', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce72', 'processed_result_id': '6936ec1f63b20b32e203b0cc', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c880', 'processed_result_id': '6936ec1f768ec624a89fe4c5', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d498', 'processed_result_id': '6936ec1fed11bd1165b8b3be', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce74', 'processed_result_id': '6936ec20768ec624a89fe4c6', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c882', 'processed_result_id': '6936ec20e9c561e8680b9604', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7df', 'processed_result_id': '6936ec2063b20b32e203b0cd', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c884', 'processed_result_id': '6936ec20ed11bd1165b8b3bf', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce76', 'processed_result_id': '6936ec21768ec624a89fe4c7', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49a', 'processed_result_id': '6936ec2163b20b32e203b0ce', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7e1', 'processed_result_id': '6936ec21e9c561e8680b9605', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c886', 'processed_result_id': '6936ec21ed11bd1165b8b3c0', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49c', 'processed_result_id': '6936ec21768ec624a89fe4c8', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7e3', 'processed_result_id': '6936ec21e9c561e8680b9606', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce78', 'processed_result_id': '6936ec2163b20b32e203b0cf', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e5', 'processed_result_id': '6936ec22ed11bd1165b8b3c1', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49e', 'processed_result_id': '6936ec22768ec624a89fe4c9', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c888', 'processed_result_id': '6936ec22e9c561e8680b9607', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7a', 'processed_result_id': '6936ec2263b20b32e203b0d0', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a0', 'processed_result_id': '6936ec22ed11bd1165b8b3c2', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e7', 'processed_result_id': '6936ec23768ec624a89fe4ca', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88a', 'processed_result_id': '6936ec23e9c561e8680b9608', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7c', 'processed_result_id': '6936ec2363b20b32e203b0d1', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a2', 'processed_result_id': '6936ec23ed11bd1165b8b3c3', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e9', 'processed_result_id': '6936ec24768ec624a89fe4cb', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88c', 'processed_result_id': '6936ec24e9c561e8680b9609', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7e', 'processed_result_id': '6936ec2463b20b32e203b0d2', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a4', 'processed_result_id': '6936ec24ed11bd1165b8b3c4', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7eb', 'processed_result_id': '6936ec25768ec624a89fe4cc', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88e', 'processed_result_id': '6936ec25e9c561e8680b960a', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce80', 'processed_result_id': '6936ec2563b20b32e203b0d3', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a6', 'processed_result_id': '6936ec25ed11bd1165b8b3c5', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7ed', 'processed_result_id': '6936ec25768ec624a89fe4cd', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce82', 'processed_result_id': '6936ec2663b20b32e203b0d4', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c890', 'processed_result_id': '6936ec26e9c561e8680b960b', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a8', 'processed_result_id': '6936ec26ed11bd1165b8b3c6', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7ef', 'processed_result_id': '6936ec26768ec624a89fe4ce', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c892', 'processed_result_id': '6936ec26e9c561e8680b960c', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce84', 'processed_result_id': '6936ec2663b20b32e203b0d5', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4aa', 'processed_result_id': '6936ec27ed11bd1165b8b3c7', 'status': 'success'}]}

## Calculating Exposure Indicators

In [64]:
res = requests.post("http://localhost:8011/init_exposure_indicator_collection")
print(res.json())

{'status': 'success', 'message': 'All 0 exposure indicator records have been deleted.'}

In [65]:
steady_state_data = solve_steady_state_res.json()
rate_constant_data = generate_rate_constant_res.json()
flow_estimation_data = flow_estimation_res.json()
processed_result_data = process_result_res.json()

# Lookup 1: model_id -> flow_estimation_id
flow_estimation_lookup = {
    item['model_id']: item['flow_estimation_id']
    for item in flow_estimation_data.get('results', [])
}

# Lookup 2: model_id -> rate_constant_id
rate_constant_lookup = {
    item['model_id']: item['rate_constant_id']
    for item in rate_constant_data.get('results', [])
}

# Lookup 3: model_id -> particle_state_id (and result_id, though not needed here)
steady_state_lookup = {
    item['model_id']: item['particle_state_id']
    for item in steady_state_data.get('results', [])
}

exposure_inidcator_endpoint_inputs = []

for item in processed_result_data.get('results', []):
    model_id = item.get('model_id')
    processed_result_id = item.get('processed_result_id')

    # Ensure the model_id exists in all three lookup dictionaries
    if (model_id in flow_estimation_lookup and
        model_id in rate_constant_lookup and
        model_id in steady_state_lookup):
        
        # Build the final dictionary
        combined_input = {
            'model_id': model_id,
            'processed_result_id': processed_result_id,
            # Retrieve IDs from the three lookups:
            'flow_estimation_id': flow_estimation_lookup[model_id],
            'rate_constant_id': rate_constant_lookup[model_id],
            'particle_state_id': steady_state_lookup[model_id]
        }
        
        exposure_inidcator_endpoint_inputs.append(combined_input)

In [66]:
exposure_indicator_res = requests.post("http://localhost:8011/calculate_exposure_indicator/batch",
    json = {
        "items":exposure_inidcator_endpoint_inputs

    })
if exposure_indicator_res.ok:
    print("Response:", exposure_indicator_res.json())
else:
    print("Error:", exposure_indicator_res.status_code, exposure_indicator_res.text)

Response: {'count': 100, 'successful': 100, 'failed': 0, 'results': [{'model_id': '6936eb6c35547f4955bed7c1', 'exposure_indicator_id': '6936ecad75ccc54eae9e026b', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47a', 'exposure_indicator_id': '6936ecade9381d6df93d303a', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c864', 'exposure_indicator_id': '6936ecadc935070a55411356', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7bf', 'exposure_indicator_id': '6936ecad1c00e3dd302f4679', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c3', 'exposure_indicator_id': '6936ecad75ccc54eae9e026c', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce54', 'exposure_indicator_id': '6936ecad75ccc54eae9e026d', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47c', 'exposure_indicator_id': '6936ecad1c00e3dd302f467a', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c862', 'exposure_indicator_id': '6936ecadc935070a55411357', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce58', 'exposure_indicator_id': '6936ecade9381d6df93d303b', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce56', 'exposure_indicator_id': '6936ecad75ccc54eae9e026e', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d47e', 'exposure_indicator_id': '6936ecad1c00e3dd302f467b', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c5', 'exposure_indicator_id': '6936ecadc935070a55411358', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5a', 'exposure_indicator_id': '6936ecade9381d6df93d303c', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c866', 'exposure_indicator_id': '6936ecad75ccc54eae9e026f', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c7', 'exposure_indicator_id': '6936ecad1c00e3dd302f467c', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d480', 'exposure_indicator_id': '6936ecadc935070a55411359', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c868', 'exposure_indicator_id': '6936ecade9381d6df93d303d', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c86a', 'exposure_indicator_id': '6936ecad75ccc54eae9e0270', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5c', 'exposure_indicator_id': '6936ecad1c00e3dd302f467d', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d482', 'exposure_indicator_id': '6936ecadc935070a5541135a', 'status': 'success'}, {'model_id': '6936eb6c35547f4955bed7c9', 'exposure_indicator_id': '6936ecade9381d6df93d303e', 'status': 'success'}, {'model_id': '6936eb6cc77c0ff1798fce5e', 'exposure_indicator_id': '6936ecad75ccc54eae9e0271', 'status': 'success'}, {'model_id': '6936eb6cb19f000d48b1c86c', 'exposure_indicator_id': '6936ecad1c00e3dd302f467e', 'status': 'success'}, {'model_id': '6936eb6cfc480e63d6f0d484', 'exposure_indicator_id': '6936ecadc935070a5541135b', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cb', 'exposure_indicator_id': '6936ecade9381d6df93d303f', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c86e', 'exposure_indicator_id': '6936ecad1c00e3dd302f467f', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce60', 'exposure_indicator_id': '6936ecadc935070a5541135c', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d486', 'exposure_indicator_id': '6936ecade9381d6df93d3040', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cd', 'exposure_indicator_id': '6936ecad75ccc54eae9e0272', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c870', 'exposure_indicator_id': '6936ecad75ccc54eae9e0273', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce62', 'exposure_indicator_id': '6936ecad1c00e3dd302f4680', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d488', 'exposure_indicator_id': '6936ecadc935070a5541135d', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7cf', 'exposure_indicator_id': '6936ecade9381d6df93d3041', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c872', 'exposure_indicator_id': '6936ecad75ccc54eae9e0274', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce64', 'exposure_indicator_id': '6936ecad1c00e3dd302f4681', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c874', 'exposure_indicator_id': '6936ecadc935070a5541135e', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48a', 'exposure_indicator_id': '6936ecade9381d6df93d3042', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce66', 'exposure_indicator_id': '6936ecae75ccc54eae9e0275', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d1', 'exposure_indicator_id': '6936ecae1c00e3dd302f4682', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48c', 'exposure_indicator_id': '6936ecaec935070a5541135f', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d3', 'exposure_indicator_id': '6936ecaee9381d6df93d3043', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c876', 'exposure_indicator_id': '6936ecae75ccc54eae9e0276', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce68', 'exposure_indicator_id': '6936ecaec935070a55411360', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c878', 'exposure_indicator_id': '6936ecae1c00e3dd302f4683', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d5', 'exposure_indicator_id': '6936ecaee9381d6df93d3044', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d48e', 'exposure_indicator_id': '6936ecae75ccc54eae9e0277', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce6a', 'exposure_indicator_id': '6936ecae1c00e3dd302f4684', 'status': 'success'}, {'model_id': '6936eb6dfc480e63d6f0d490', 'exposure_indicator_id': '6936ecaec935070a55411361', 'status': 'success'}, {'model_id': '6936eb6d35547f4955bed7d7', 'exposure_indicator_id': '6936ecaee9381d6df93d3045', 'status': 'success'}, {'model_id': '6936eb6db19f000d48b1c87a', 'exposure_indicator_id': '6936ecae75ccc54eae9e0278', 'status': 'success'}, {'model_id': '6936eb6dc77c0ff1798fce6c', 'exposure_indicator_id': '6936ecaec935070a55411362', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c87c', 'exposure_indicator_id': '6936ecae1c00e3dd302f4685', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d492', 'exposure_indicator_id': '6936ecaee9381d6df93d3046', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7d9', 'exposure_indicator_id': '6936ecae75ccc54eae9e0279', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce6e', 'exposure_indicator_id': '6936ecaec935070a55411363', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c87e', 'exposure_indicator_id': '6936ecae1c00e3dd302f4686', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce70', 'exposure_indicator_id': '6936ecaee9381d6df93d3047', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7db', 'exposure_indicator_id': '6936ecae75ccc54eae9e027a', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d494', 'exposure_indicator_id': '6936ecae1c00e3dd302f4687', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7dd', 'exposure_indicator_id': '6936ecaec935070a55411364', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c880', 'exposure_indicator_id': '6936ecaee9381d6df93d3048', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d496', 'exposure_indicator_id': '6936ecae75ccc54eae9e027b', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce72', 'exposure_indicator_id': '6936ecaec935070a55411365', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d498', 'exposure_indicator_id': '6936ecae1c00e3dd302f4688', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce74', 'exposure_indicator_id': '6936ecaee9381d6df93d3049', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c882', 'exposure_indicator_id': '6936ecae1c00e3dd302f4689', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7df', 'exposure_indicator_id': '6936ecaec935070a55411366', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c884', 'exposure_indicator_id': '6936ecaee9381d6df93d304a', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce76', 'exposure_indicator_id': '6936ecae75ccc54eae9e027c', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7e1', 'exposure_indicator_id': '6936ecae75ccc54eae9e027d', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49a', 'exposure_indicator_id': '6936ecae1c00e3dd302f468a', 'status': 'success'}, {'model_id': '6936eb6eb19f000d48b1c886', 'exposure_indicator_id': '6936ecaec935070a55411367', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49c', 'exposure_indicator_id': '6936ecae75ccc54eae9e027e', 'status': 'success'}, {'model_id': '6936eb6e35547f4955bed7e3', 'exposure_indicator_id': '6936ecaee9381d6df93d304b', 'status': 'success'}, {'model_id': '6936eb6ec77c0ff1798fce78', 'exposure_indicator_id': '6936ecae1c00e3dd302f468b', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e5', 'exposure_indicator_id': '6936ecaec935070a55411368', 'status': 'success'}, {'model_id': '6936eb6efc480e63d6f0d49e', 'exposure_indicator_id': '6936ecae75ccc54eae9e027f', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c888', 'exposure_indicator_id': '6936ecaee9381d6df93d304c', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7a', 'exposure_indicator_id': '6936ecae1c00e3dd302f468c', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a0', 'exposure_indicator_id': '6936ecaec935070a55411369', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e7', 'exposure_indicator_id': '6936ecae75ccc54eae9e0280', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88a', 'exposure_indicator_id': '6936ecaee9381d6df93d304d', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7c', 'exposure_indicator_id': '6936ecaec935070a5541136a', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a2', 'exposure_indicator_id': '6936ecae1c00e3dd302f468d', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7e9', 'exposure_indicator_id': '6936ecae75ccc54eae9e0281', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88c', 'exposure_indicator_id': '6936ecaee9381d6df93d304e', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce7e', 'exposure_indicator_id': '6936ecaec935070a5541136b', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a4', 'exposure_indicator_id': '6936ecae1c00e3dd302f468e', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7eb', 'exposure_indicator_id': '6936ecae75ccc54eae9e0282', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c88e', 'exposure_indicator_id': '6936ecaee9381d6df93d304f', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce80', 'exposure_indicator_id': '6936ecae75ccc54eae9e0283', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a6', 'exposure_indicator_id': '6936ecaec935070a5541136c', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7ed', 'exposure_indicator_id': '6936ecae1c00e3dd302f468f', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c890', 'exposure_indicator_id': '6936ecaee9381d6df93d3050', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce82', 'exposure_indicator_id': '6936ecaec935070a5541136d', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4a8', 'exposure_indicator_id': '6936ecae75ccc54eae9e0284', 'status': 'success'}, {'model_id': '6936eb6f35547f4955bed7ef', 'exposure_indicator_id': '6936ecae1c00e3dd302f4690', 'status': 'success'}, {'model_id': '6936eb6fb19f000d48b1c892', 'exposure_indicator_id': '6936ecaee9381d6df93d3051', 'status': 'success'}, {'model_id': '6936eb6fc77c0ff1798fce84', 'exposure_indicator_id': '6936ecaec935070a5541136e', 'status': 'success'}, {'model_id': '6936eb6ffc480e63d6f0d4aa', 'exposure_indicator_id': '6936ecae1c00e3dd302f4691', 'status': 'success'}]}

In [67]:
import pandas as pd
from bson import ObjectId
exposure_indicator_id = exposure_indicator_res.json()['results'][0]["exposure_indicator_id"]
doc = exposure_indicator_collection.find_one({"_id": ObjectId(exposure_indicator_id)})
overall_df = pd.DataFrame(doc["overall_exposure_indicators"])
size_df = pd.DataFrame(doc["size_fraction_indicators"])

In [68]:
overall_df

,Overall exposure indicators,Overall persistence (years),Overall residence time (years)
0,Mass,0.214848,0.000153
1,Number,127233.456926,2.696977

In [69]:
size_df

   Size (um)    Pov (years)  Tov (years)
0        0.5  125525.744200     2.691524
1        5.0   74988.256350     2.541914
2       50.0    9164.452091     2.165359
3      500.0     171.466368     1.412756
4     5000.0       0.209564     0.000150

In [33]:
from bson import ObjectId
processed_result_id = process_result_res.json()["results"][0]["processed_result_id"]
processed_result_doc = processed_result_collection.find_one({"_id":ObjectId(processed_result_id)})

for key in processed_result_doc:
    print(key)

_id
model_id
processed_result
results_by_comp

In [34]:
for key in processed_result_doc["results_by_comp"]:
    print(key)

{'index': 0, 'Compartments': 'Ocean_Surface_Water', 'mass_g': 44310038.74797882, 'number_of_particles': 2.5156098572787376e+17, '%_mass': 14.527145831150015, '%_number': 0.0076392175501483065, 'Concentration_g_m3': 2.718407285152075e-08, 'Concentration_num_m3': 154.33189308458518, 'inflows_g_s': {'k_rising': 119205.37221596707, 'k_mixing': 3085.5008834871624, 'k_advective_transport': 0.5860937516029803, 'k_dry_deposition': 1.7646287926615547e-05, 'k_wet_deposition': 3.9539563598225085e-07}, 'inflows_num_s': {'k_rising': 2006106.8668187978, 'k_mixing': 694344631346637.8, 'k_advective_transport': 5300458187.055222, 'k_dry_deposition': 7100089.136479786, 'k_wet_deposition': 5647801.794989964}, 'outflows_g_s': {'k_discorporation': 93.81650582826217, 'k_advective_transport': 1.824051288337042, 'k_settling': 0.11169001603228164, 'k_rising': 0.0, 'k_mixing': 122295.7069444215, 'k_sea_spray_aerosol': 1.9693350554657252e-05, 'k_beaching': 0.0}, 'outflows_num_s': {'k_discorporation': 4654253.904579373, 'k_advective_transport': 10355670025.975664, 'k_settling': 1543840584878.9705, 'k_rising': 0.0, 'k_mixing': 694308320608931.6, 'k_sea_spray_aerosol': 111804.88254572172, 'k_beaching': 0.0}, 'Total_inflows_g_s': 122291.45921124752, 'Total_inflows_num_s': 694349946558822.5, 'Total_outflows_g_s': 122391.4592112475, 'Total_outflows_num_s': 695862521629895.4}
{'index': 1, 'Compartments': 'Ocean_Mixed_Water', 'mass_g': 22358702.0542548, 'number_of_particles': 5.0314828358452e+18, '%_mass': 7.330350740264446, '%_number': 0.1527923412751985, 'Concentration_g_m3': 6.858497562654847e-10, 'Concentration_num_m3': 154.3399642897301, 'inflows_g_s': {'k_settling': 0.11169001603228164, 'k_mixing': 122295.70701610764, 'k_rising': 0.00695695702787715, 'k_advective_transport': 0.10424904327465487}, 'inflows_num_s': {'k_settling': 1543840584878.9705, 'k_mixing': 694309376253631.4, 'k_rising': 14.254653500299153, 'k_advective_transport': 35358788599.43202}, 'outflows_g_s': {'k_discorporation': 4.63117651893918, 'k_advective_transport': 0.3065748410506716, 'k_settling': 0.11198030886789151, 'k_rising': 119205.37221596707, 'k_mixing': 3085.5079644881025}, 'outflows_num_s': {'k_discorporation': 9324667.731932238, 'k_advective_transport': 68989964037.50934, 'k_settling': 1546395883501.823, 'k_rising': 2006106.8668187978, 'k_mixing': 694346224817251.8}, 'Total_inflows_g_s': 122295.92991212397, 'Total_inflows_num_s': 695888575627124.0, 'Total_outflows_g_s': 122295.92991212403, 'Total_outflows_num_s': 695961621995565.6}
{'index': 2, 'Compartments': 'Ocean_Column_Water', 'mass_g': 9095799.641961886, 'number_of_particles': 1.3394404302684455e+20, '%_mass': 2.9820783638048556, '%_number': 4.067513415356735, 'Concentration_g_m3': 6.943358505314417e-12, 'Concentration_num_m3': 102.24736108919433, 'inflows_g_s': {'k_settling': 0.11198030886789151, 'k_mixing': 0.007081000940582494, 'k_sediment_resuspension': 0.0022372840003552965}, 'inflows_num_s': {'k_settling': 1546395883501.823, 'k_mixing': 1593470614.112175, 'k_sediment_resuspension': 30911583496.720665}, 'outflows_g_s': {'k_discorporation': 4.381031970460527e-05, 'k_advective_transport': 0.0, 'k_settling': 0.11422614031182812, 'k_rising': 0.00695695702787715, 'k_mixing': 7.168614941943828e-05}, 'outflows_num_s': {'k_discorporation': 412293484.7461027, 'k_advective_transport': 0.0, 'k_settling': 1577438295976.7046, 'k_rising': 14.254653500299153, 'k_mixing': 1055644699.7764995}, 'Total_inflows_g_s': 0.12129859380882929, 'Total_inflows_num_s': 1578900937612.6558, 'Total_outflows_g_s': 0.1212985938088293, 'Total_outflows_num_s': 1578906234175.482}
{'index': 3, 'Compartments': 'Coast_Surface_Water', 'mass_g': 586093.7516029802, 'number_of_particles': 5300458187055221.0, '%_mass': 0.19215215424858284, '%_number': 0.0001609603853682664, 'Concentration_g_m3': 8.73463117143041e-09, 'Concentration_num_m3': 78.99341560439973, 'inflows_g_s': {'k_advective_transport': 1.8240512911368012, 'k_rising': 3144.297633764665, 'k_mixing': 86.25383929462718, 'k_runoff_transport': 7.747495556013658e-05, 'k_dry_deposition': 1.4506764307769837e-06, 'k_wet_deposition': 3.250491731387829e-08}, 'inflows_num_s': {'k_advective_transport': 10355672321.840351, 'k_rising': 59033.95247559082, 'k_mixing': 29255244688174.36, 'k_runoff_transport': 250144923.08181787, 'k_dry_deposition': 583688.3093793198, 'k_wet_deposition': 464297.81627524877}, 'outflows_g_s': {'k_discorporation': 1.349429892747859, 'k_advective_transport': 0.5860937516029803, 'k_settling': 0.004550243033588702, 'k_rising': 0.0, 'k_mixing': 3230.4159924418223, 'k_sea_spray_aerosol': 5.209722236470937e-07, 'k_beaching': 0.019536458386766015}, 'outflows_num_s': {'k_discorporation': 96328.30293479635, 'k_advective_transport': 5300458187.055222, 'k_settling': 64133986165.95277, 'k_rising': 0.0, 'k_mixing': 29214924827131.2, 'k_sea_spray_aerosol': 4711.518388493532, 'k_beaching': 176681939.56850743}, 'Total_inflows_g_s': 3232.3756033085656, 'Total_inflows_num_s': 29265851612439.36, 'Total_outflows_g_s': 3232.375603308566, 'Total_outflows_num_s': 29284536054463.6}
{'index': 4, 'Compartments': 'Coast_Column_Water', 'mass_g': 312513.91048777965, 'number_of_particles': 1.059972633629506e+17, '%_mass': 0.10245838821628257, '%_number': 0.0032188463255024636, 'Concentration_g_m3': 2.3321933618491015e-10, 'Concentration_num_m3': 79.10243534548552, 'inflows_g_s': {'k_advective_transport': 0.3065748440593855, 'k_settling': 0.004550243033588702, 'k_mixing': 3230.4159924418223, 'k_sediment_resuspension': 0.00041414430401469777}, 'inflows_num_s': {'k_advective_transport': 68989986995.68318, 'k_settling': 64133986165.95277, 'k_mixing': 29214924827131.2, 'k_sediment_resuspension': 5833928914.584787}, 'outflows_g_s': {'k_discorporation': 0.06725213055168744, 'k_advective_transport': 0.10424904327465487, 'k_settling': 0.004557440101024544, 'k_rising': 3144.297633764665, 'k_mixing': 86.25383929462718}, 'outflows_num_s': {'k_discorporation': 192825.24487198645, 'k_advective_transport': 35358788599.43202, 'k_settling': 64188579977.74357, 'k_rising': 59033.95247559082, 'k_mixing': 29255244688174.36}, 'Total_inflows_g_s': 3230.7275316732193, 'Total_inflows_num_s': 29353882729207.42, 'Total_outflows_g_s': 3230.72753167322, 'Total_outflows_num_s': 29354792308610.73}
{'index': 5, 'Compartments': 'Surface_Freshwater', 'mass_g': 0.21472729220586623, 'number_of_particles': 176081147500.39508, '%_mass': 7.03988255470634e-08, '%_number': 5.347101770742613e-09, 'Concentration_g_m3': 2.372677261943273e-14, 'Concentration_num_m3': 0.01945648038678399, 'inflows_g_s': {'k_rising': 0.0012840433418054953, 'k_mixing': 0.0001546045472704026, 'k_runoff_transport': 2.459063114116753e-07, 'k_dry_deposition': 4.898739439750636e-07, 'k_wet_deposition': 1.097647394367905e-08}, 'inflows_num_s': {'k_rising': 0.5295347598234944, 'k_mixing': 1179719383.1133642, 'k_runoff_transport': 2937425.246280124, 'k_dry_deposition': 197103.70148816585, 'k_wet_deposition': 156787.13571981346}, 'outflows_g_s': {'k_discorporation': 4.6781518590683815e-07, 'k_advective_transport': 2.799759169093062e-09, 'k_settling': 2.5117308084897736e-07, 'k_rising': 0.0, 'k_mixing': 0.0014386728577793035}, 'outflows_num_s': {'k_discorporation': 1.4847988558005745, 'k_advective_transport': 2295.8646856405117, 'k_settling': 3271043.112223494, 'k_rising': 0.0, 'k_mixing': 1179743688.2526472}, 'Total_inflows_g_s': 0.0014393946458052284, 'Total_inflows_num_s': 1183010699.7263873, 'Total_outflows_g_s': 0.0014393946458052284, 'Total_outflows_num_s': 1183017028.7143552}
{'index': 6, 'Compartments': 'Bulk_Freshwater', 'mass_g': 0.2307530556274665, 'number_of_particles': 1760775198676.6636, '%_mass': 7.565290811749936e-08, '%_number': 5.346991609480814e-08, 'Concentration_g_m3': 2.549757520745487e-15, 'Concentration_num_m3': 0.01945607954338855, 'inflows_g_s': {'k_settling': 2.5117308084897736e-07, 'k_mixing': 0.0014386728577793035, 'k_sediment_resuspension': 1.2265482107439763e-10}, 'inflows_num_s': {'k_settling': 3271043.112223494, 'k_mixing': 1179743688.2526472, 'k_sediment_resuspension': 1760.774532408271}, 'outflows_g_s': {'k_discorporation': 2.115798929165398e-08, 'k_advective_transport': 3.0087138744796737e-09, 'k_settling': 2.520977359095497e-07, 'k_rising': 0.0012840433418054953, 'k_mixing': 0.0001546045472704026}, 'outflows_num_s': {'k_discorporation': 1.4871436820017985, 'k_advective_transport': 22958.173861198484, 'k_settling': 3274408.496506907, 'k_rising': 0.5295347598234944, 'k_mixing': 1179719383.1133642}, 'Total_inflows_g_s': 0.0014389241535149736, 'Total_inflows_num_s': 1183016492.1394029, 'Total_outflows_g_s': 0.0014389241535149736, 'Total_outflows_num_s': 1183016751.8004107}
{'index': 7, 'Compartments': 'Sediment_Freshwater', 'mass_g': 0.12265482107439761, 'number_of_particles': 1760774532408.2712, '%_mass': 4.021265886892648e-08, '%_number': 5.346989586206345e-08, 'Concentration_g_m3': 1.3553018903248356e-13, 'Concentration_num_m3': 1.9456072181306863, 'inflows_g_s': {'k_settling': 2.520977359095497e-07}, 'inflows_num_s': {'k_settling': 3274408.496506907}, 'outflows_g_s': {'k_discorporation': 3.083927317847638e-14, 'k_sediment_resuspension': 1.2265482107439763e-10, 'k_burial': 2.5197505024920207e-07}, 'outflows_num_s': {'k_discorporation': 0.14871378486743742, 'k_sediment_resuspension': 1760.774532408271, 'k_burial': 3272647.581376196}, 'Total_inflows_g_s': 2.520977359095497e-07, 'Total_inflows_num_s': 3274408.496506907, 'Total_outflows_g_s': 2.520977359095496e-07, 'Total_outflows_num_s': 3274408.504622389}
{'index': 8, 'Compartments': 'Sediment_Ocean', 'mass_g': 223728400.03552967, 'number_of_particles': 3.0911583496720666e+21, '%_mass': 73.34985898729914, '%_number': 93.87000550493477, 'Concentration_g_m3': 2.2852747705365644e-05, 'Concentration_num_m3': 315746511.7131835, 'inflows_g_s': {'k_settling': 0.11422614031182812}, 'inflows_num_s': {'k_settling': 1577438295976.7046}, 'outflows_g_s': {'k_discorporation': 0.00012465629370801975, 'k_sediment_resuspension': 0.0022372840003552965, 'k_burial': 0.11186420001776484}, 'outflows_num_s': {'k_discorporation': 983076103.9488368, 'k_sediment_resuspension': 30911583496.720665, 'k_burial': 1545579174836.0334}, 'Total_inflows_g_s': 0.11422614031182812, 'Total_inflows_num_s': 1577438295976.7046, 'Total_outflows_g_s': 0.11422614031182816, 'Total_outflows_num_s': 1577473834436.703}
{'index': 9, 'Compartments': 'Sediment_Coast', 'mass_g': 4141443.0401469776, 'number_of_particles': 5.833928914584787e+19, '%_mass': 1.357781412420018, '%_number': 1.7716042899761797, 'Concentration_g_m3': 1.5453145672190212e-06, 'Concentration_num_m3': 21768391.472331297, 'inflows_g_s': {'k_settling': 0.004557440101024544}, 'inflows_num_s': {'k_settling': 64188579977.74357}, 'outflows_g_s': {'k_discorporation': 1.8527568628687874e-06, 'k_sediment_resuspension': 0.00041414430401469777, 'k_burial': 0.004141443040146978}, 'outflows_num_s': {'k_discorporation': 15877912.826307459, 'k_sediment_resuspension': 5833928914.584787, 'k_burial': 58339289145.847885}, 'Total_inflows_g_s': 0.004557440101024544, 'Total_inflows_num_s': 64188579977.74357, 'Total_outflows_g_s': 0.004557440101024544, 'Total_outflows_num_s': 64189095973.25898}
{'index': 10, 'Compartments': 'Beaches_Soil_Surface', 'mass_g': 121265.14783325724, 'number_of_particles': 3.915311839541497e+17, '%_mass': 0.039757051372248, '%_number': 0.011889728779837074, 'Concentration_g_m3': 35.25149646315618, 'Concentration_num_m3': 113817204637834.19, 'inflows_g_s': {'k_beaching': 0.019536458386766015, 'k_soil_convection': 0.0004508421490197281, 'k_dry_deposition': 1.8620622842809044e-14, 'k_wet_deposition': 4.172272968647063e-16}, 'inflows_num_s': {'k_beaching': 176681939.56850743, 'k_soil_convection': 4722057625.266074, 'k_dry_deposition': 0.007492118598003207, 'k_wet_deposition': 0.005959643611891251}, 'outflows_g_s': {'k_discorporation': 0.018372555872616252, 'k_runoff_transport': 7.747495556013658e-05, 'k_percolation': 0.0, 'k_soil_air_resuspension': 7.981454397872127e-06, 'k_soil_convection': 0.001529288253230522}, 'outflows_num_s': {'k_discorporation': 438956.6429690738, 'k_runoff_transport': 250144923.08181787, 'k_percolation': 0.0, 'k_soil_air_resuspension': 19590587.254522484, 'k_soil_convection': 4937643264.310666}, 'Total_inflows_g_s': 0.01998730053580478, 'Total_inflows_num_s': 4898739564.848033, 'Total_outflows_g_s': 0.019987300535804782, 'Total_outflows_num_s': 5207817731.289975}
{'index': 11, 'Compartments': 'Beaches_Deep_Soil', 'mass_g': 357495.9771962602, 'number_of_particles': 3.7443628746603244e+18, '%_mass': 0.11720585992528493, '%_number': 0.11370603634528333, 'Concentration_g_m3': 10.392324918495937, 'Concentration_num_m3': 108847757984311.75, 'inflows_g_s': {'k_percolation': 0.0, 'k_soil_convection': 0.001529288253230522}, 'inflows_num_s': {'k_percolation': 0.0, 'k_soil_convection': 4937643264.310666}, 'outflows_g_s': {'k_discorporation': 0.001055903996759807, 'k_sequestration_deep_soils': 2.2542107450986404e-05, 'k_soil_convection': 0.0004508421490197281}, 'outflows_num_s': {'k_discorporation': 419003.84859122836, 'k_sequestration_deep_soils': 236102881.2633038, 'k_soil_convection': 4722057625.266074}, 'Total_inflows_g_s': 0.001529288253230522, 'Total_inflows_num_s': 4937643264.310666, 'Total_outflows_g_s': 0.0015292882532305216, 'Total_outflows_num_s': 4958579510.377969}
{'index': 12, 'Compartments': 'Background_Soil_Surface', 'mass_g': 227.03711971345862, 'number_of_particles': 2712027045831133.0, '%_mass': 7.443463017310323e-05, '%_number': 8.235682709321829e-05, 'Concentration_g_m3': 2.600654292250385e-10, 'Concentration_num_m3': 3106.5601899554786, 'inflows_g_s': {'k_soil_convection': 2.4613635054044065e-06, 'k_dry_deposition': 4.725524343538459e-06, 'k_wet_deposition': 1.058835552799095e-07}, 'inflows_num_s': {'k_soil_convection': 32576984.087163836, 'k_dry_deposition': 1901342.8883886049, 'k_wet_deposition': 1512432.8119712397}, 'outflows_g_s': {'k_discorporation': 4.272352630126187e-06, 'k_runoff_transport': 1.4505149315026527e-07, 'k_percolation': 0.0, 'k_soil_air_resuspension': 1.2176937893259838e-08, 'k_soil_convection': 2.8631903430530617e-06}, 'outflows_num_s': {'k_discorporation': 3013.2997097082807, 'k_runoff_transport': 1732683.9459476678, 'k_percolation': 0.0, 'k_soil_air_resuspension': 135698.60769814858, 'k_soil_convection': 34201674.411314845}, 'Total_inflows_g_s': 7.292771404222775e-06, 'Total_inflows_num_s': 35990759.78752368, 'Total_outflows_g_s': 7.292771404222774e-06, 'Total_outflows_num_s': 36073070.26467037}
{'index': 13, 'Compartments': 'Background_Soil', 'mass_g': 1951.7419866642872, 'number_of_particles': 2.5831969760746664e+16, '%_mass': 0.0006398829986657115, '%_number': 0.000784446110275083, 'Concentration_g_m3': 2.2356723787677972e-10, 'Concentration_num_m3': 2958.988517840396, 'inflows_g_s': {'k_percolation': 0.0, 'k_soil_convection': 2.8631903430530617e-06}, 'inflows_num_s': {'k_percolation': 0.0, 'k_soil_convection': 34201674.411314845}, 'outflows_g_s': {'k_discorporation': 2.787586623784348e-07, 'k_sequestration_deep_soils': 1.230681752702203e-07, 'k_soil_convection': 2.4613635054044065e-06}, 'outflows_num_s': {'k_discorporation': 2869.7336180081534, 'k_sequestration_deep_soils': 1628849.2043581926, 'k_soil_convection': 32576984.087163836}, 'Total_inflows_g_s': 2.8631903430530617e-06, 'Total_inflows_num_s': 34201674.411314845, 'Total_outflows_g_s': 2.8631903430530617e-06, 'Total_outflows_num_s': 34208703.02514004}
{'index': 14, 'Compartments': 'Impacted_Soil_Surface', 'mass_g': 157.85971553959837, 'number_of_particles': 1885682035302975.2, '%_mass': 5.175466267476938e-05, '%_number': 5.726299432483791e-05, 'Concentration_g_m3': 2.600654292250385e-10, 'Concentration_num_m3': 3106.5601899554786, 'inflows_g_s': {'k_soil_convection': 1.7113947855446448e-06, 'k_dry_deposition': 3.2856738562747357e-06, 'k_wet_deposition': 7.362121197583628e-08}, 'inflows_num_s': {'k_soil_convection': 22650892.715817243, 'k_dry_deposition': 1322010.461915101, 'k_wet_deposition': 1051599.9047726719}, 'outflows_g_s': {'k_discorporation': 2.970581954738369e-06, 'k_runoff_transport': 1.0085481826141009e-07, 'k_percolation': 0.0, 'k_soil_air_resuspension': 8.466668157169212e-09, 'k_soil_convection': 1.990786412638268e-06}, 'outflows_num_s': {'k_discorporation': 2095.157988308049, 'k_runoff_transport': 1204741.3003324564, 'k_percolation': 0.0, 'k_soil_air_resuspension': 94351.72379470355, 'k_soil_convection': 23780545.667431965}, 'Total_inflows_g_s': 5.070689853795217e-06, 'Total_inflows_num_s': 25024503.082505018, 'Total_outflows_g_s': 5.0706898537952165e-06, 'Total_outflows_num_s': 25081733.849547435}
{'index': 15, 'Compartments': 'Impacted_Soil', 'mass_g': 1357.0531339120532, 'number_of_particles': 1.796106030329121e+16, '%_mass': 0.000444912921179939, '%_number': 0.0005454281660217359, 'Concentration_g_m3': 2.2356723787677972e-10, 'Concentration_num_m3': 2958.988517840396, 'inflows_g_s': {'k_percolation': 0.0, 'k_soil_convection': 1.990786412638268e-06}, 'inflows_num_s': {'k_percolation': 0.0, 'k_soil_convection': 23780545.667431965}, 'outflows_g_s': {'k_discorporation': 1.938218878163917e-07, 'k_sequestration_deep_soils': 8.556973927723224e-08, 'k_soil_convection': 1.7113947855446448e-06}, 'outflows_num_s': {'k_discorporation': 1995.3359749495412, 'k_sequestration_deep_soils': 1132544.6357908624, 'k_soil_convection': 22650892.715817243}, 'Total_inflows_g_s': 1.990786412638268e-06, 'Total_inflows_num_s': 23780545.667431965, 'Total_outflows_g_s': 1.990786412638269e-06, 'Total_outflows_num_s': 23785432.687583055}
{'index': 16, 'Compartments': 'Air', 'mass_g': 0.12146342236420736, 'number_of_particles': 1734974472214.4304, '%_mass': 3.982205612302462e-08, '%_number': 5.268641875786384e-08, 'Concentration_g_m3': 3.969392887719195e-20, 'Concentration_num_m3': 5.669851216387027e-07, 'inflows_g_s': {'k_sea_spray_aerosol': 2.0214322778304346e-05, 'k_soil_air_resuspension': 8.00209800392255e-06}, 'inflows_num_s': {'k_sea_spray_aerosol': 116516.40093421524, 'k_soil_air_resuspension': 19820637.586015336}, 'outflows_g_s': {'k_discorporation': 2.467512711997165e-12, 'k_wind_trasport': 0.0, 'k_dry_deposition': 2.7598036519801403e-05, 'k_wet_deposition': 6.183817949127811e-07}, 'outflows_num_s': {'k_discorporation': 0.012117868054595707, 'k_wind_trasport': 0.0, 'k_dry_deposition': 11104234.505143093, 'k_wet_deposition': 8832919.46968858}, 'Total_inflows_g_s': 2.8216420782226895e-05, 'Total_inflows_num_s': 19937153.98694955, 'Total_outflows_g_s': 2.8216420782226898e-05, 'Total_outflows_num_s': 19937153.98694954}

In [ ]:
from utopia.microservice.solve_steady_state.mass_balance_check_json_app import *
from bson import ObjectId
R_document = result_collection.find_one({'model_id':solve_steady_state_res.json()["results"][0]["model_id"]})
flow_document = flow_collection.find_one({'model_id':solve_steady_state_res.json()["results"][0]["model_id"]})
rate_constant_doc = rate_constant_collection.find_one({'_id':ObjectId(generate_rate_constant_res.json()["results"][0]["rate_constant_id"])})
massBalance_json_app(rate_constant_doc, R_document, flow_document)

Difference inflow-outflow = -7.4419860529803685

'-7.4419860529803685'

In [20]:
from bson import ObjectId
rc = rate_constant_collection.find_one({"_id": ObjectId("693548035bf07f3d425decdc")})
print(rc.keys())
print(rc)

dict_keys(['_id', 'model_id', 'system_particle_rate_constants'])

In [24]:
rate_constant_collection.count_documents({})

100

In [25]:
list(rate_constant_collection.find().limit(5))

[{'_id': ObjectId('693594ef5bf07f3d425e4cb7'),
  'model_id': '693594ead9768b8470de8d47',
  'system_particle_rate_constant_list': [{'Pcode': 'aA0_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422495264487e-13,
     'k_fragmentation': [0.0, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 2.2475769424435807e-08,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 1.1574074074074074e-06,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'bA0_Utopia',
    'RateConstants': {'k_discorporation': 1.657742249526449e-11,
     'k_fragmentation': [3.168387114321388e-10, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 6.108831761470591e-08,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 1.1574074074074074e-06,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'cA0_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422495264484e-09,
     'k_fragmentation': [2.7258826221284534e-09,
      4.4250449219293476e-10,
      0.0,
      0.0,
      0.0],
     'k_heteroaggregation': 1.1862747839710774e-05,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 1.1574074074074074e-06,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'dA0_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422495264488e-07,
     'k_fragmentation': [2.8143835205670403e-08,
      1.770017968771739e-09,
      1.7700179687717374e-09,
      0.0,
      0.0],
     'k_heteroaggregation': 0.07738097169973948,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 1.1574074074074074e-06,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'eA0_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422495264486e-05,
     'k_fragmentation': [2.902884419005627e-07,
      1.3275134765788041e-08,
      8.850089843858696e-09,
      4.425044921929319e-09,
      0.0],
     'k_heteroaggregation': 746.3861076694117,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 1.1574074074074074e-06,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'aB0_Utopia',
    'RateConstants': {'k_discorporation': 3.4916120144873546e-12,
     'k_fragmentation': [0.0, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 1.8738054691919214e-17,
     'k_biofouling': 1.1574074074074074e-06,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 2.125908565694375e-06,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'bB0_Utopia',
    'RateConstants': {'k_discorporation': 4.215989967665554e-12,
     'k_fragmentation': [5.052769882524878e-12, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 3.219267037447475e-17,
     'k_biofouling': 1.1574074074074074e-06,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 1.802983416060825e-06,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'cB0_Utopia',
    'RateConstants': {'k_discorporation': 1.6611176566819985e-10,
     'k_fragmentation': [2.7286563599769524e-11,
      4.4295476523410044e-12,
      0.0,
      0.0,
      0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 1.173171688589058e-14,
     'k_biofouling': 1.1574074074074074e-06,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'dB0_Utopia',
    'RateConstants': {'k_discorporation': 1.65774562664951e-08,
     'k_fragmentation': [2.814386387271636e-10,
      1.7700197716954022e-11,
      1.7700197716954002e-11,
      0.0,
      0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 7.737992681559413e-11,
     'k_biofouling': 1.1574074074074074e-06,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'eB0_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422529035751e-06,
     'k_fragmentation': [2.9028844219624827e-09,
      1.327513477930999e-10,
      8.850089852873328e-11,
      4.425044926436635e-11,
      0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 7.46386097485203e-07,
     'k_biofouling': 1.1574074074074074e-06,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'aC0_Utopia',
    'RateConstants': {'k_discorporation': 2.9884441760994927e-10,
     'k_fragmentation': [0.0, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 1.1118274452903358e-06,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 9.100935867123183e-06,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'bC0_Utopia',
    'RateConstants': {'k_discorporation': 5.04871197766696e-10,
     'k_fragmentation': [6.18194361451919e-10, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 2.853660739944581e-06,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 1.5063284153880052e-05,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'cC0_Utopia',
    'RateConstants': {'k_discorporation': 5.519235687990294e-09,
     'k_fragmentation': [1.7585030442121015e-09,
      2.85465518684442e-10,
      0.0,
      0.0,
      0.0],
     'k_heteroaggregation': 0.00010849780464794985,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 7.353520876424059e-05,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'dC0_Utopia',
    'RateConstants': {'k_discorporation': 3.5107254945583953e-07,
     'k_fragmentation': [1.4480321990500672e-08,
      9.106942934210596e-10,
      9.106942934210587e-10,
      0.0,
      0.0],
     'k_heteroaggregation': 0.09148973937909378,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'eC0_Utopia',
    'RateConstants': {'k_discorporation': 3.334757257369564e-05,
     'k_fragmentation': [1.455654679924644e-07,
      6.656831364670412e-09,
      4.437887576446942e-09,
      2.2189437882234567e-09,
      0.0],
     'k_heteroaggregation': 1434.3744986195652,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'aD0_Utopia',
    'RateConstants': {'k_discorporation': 3.209381417575739e-11,
     'k_fragmentation': [0.0, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 1.2693617996055035e-15,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 9.773817094705515e-06,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'bD0_Utopia',
    'RateConstants': {'k_discorporation': 5.2203467735374295e-11,
     'k_fragmentation': [6.286145344476081e-12, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 3.0367536838492283e-15,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 1.5591182214127928e-05,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'cD0_Utopia',
    'RateConstants': {'k_discorporation': 5.5244693805308e-10,
     'k_fragmentation': [1.7593366092191514e-11,
      2.8560083495123947e-12,
      0.0,
      0.0,
      0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 1.0888997964139593e-13,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 7.373940060130422e-05,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'dD0_Utopia',
    'RateConstants': {'k_discorporation': 3.510732058307388e-08,
     'k_fragmentation': [1.4480335526898578e-10,
      9.106951447502174e-12,
      9.106951447502164e-12,
      0.0,
      0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 9.148751629418209e-11,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'eD0_Utopia',
    'RateConstants': {'k_discorporation': 3.3347572641042704e-06,
     'k_fragmentation': [1.4556546813945275e-09,
      6.656831371392313e-11,
      4.4378875809282094e-11,
      2.2189437904640902e-11,
      0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 1.4343744781158992e-06,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 4.116564417177914e-08,
     'k_settling': 0,
     'k_rising': 0,
     'k_mixing': 0.00276,
     'k_sea_spray_aerosol': 4.444444444444445e-13,
     'k_beaching': 0}},
   {'Pcode': 'aA1_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422495264488e-14,
     'k_fragmentation': [0.0, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 2.2475769424435807e-08,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 3.858024691358025e-07,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 0,
     'k_rising': 1.0511154027365644e-10,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'bA1_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422495264486e-12,
     'k_fragmentation': [3.168387114321388e-11, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 6.108831761470591e-08,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 3.858024691358025e-07,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 0,
     'k_rising': 1.0511154027365646e-08,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'cA1_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422495264488e-10,
     'k_fragmentation': [2.725882622128453e-10,
      4.425044921929347e-11,
      0.0,
      0.0,
      0.0],
     'k_heteroaggregation': 1.1862747839710774e-05,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 3.858024691358025e-07,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 0,
     'k_rising': 1.0511154027365646e-06,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'dA1_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422495264488e-08,
     'k_fragmentation': [2.8143835205670405e-09,
      1.7700179687717392e-10,
      1.7700179687717377e-10,
      0.0,
      0.0],
     'k_heteroaggregation': 0.07738097169973948,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 3.858024691358025e-07,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 0,
     'k_rising': 0.00010511154027365645,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'eA1_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422495264486e-06,
     'k_fragmentation': [2.902884419005627e-08,
      1.327513476578804e-09,
      8.850089843858695e-10,
      4.425044921929319e-10,
      0.0],
     'k_heteroaggregation': 746.3861076694117,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 3.858024691358025e-07,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 0,
     'k_rising': 0.010511154027365646,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'aB1_Utopia',
    'RateConstants': {'k_discorporation': 3.4916120144873554e-13,
     'k_fragmentation': [0.0, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 1.8738054691919214e-17,
     'k_biofouling': 3.858024691358025e-07,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 1.0629542828471876e-07,
     'k_rising': 0,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'bB1_Utopia',
    'RateConstants': {'k_discorporation': 4.215989967665553e-13,
     'k_fragmentation': [5.052769882524879e-13, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 3.219267037447475e-17,
     'k_biofouling': 3.858024691358025e-07,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 9.014917080304125e-08,
     'k_rising': 0,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'cB1_Utopia',
    'RateConstants': {'k_discorporation': 1.6611176566819988e-11,
     'k_fragmentation': [2.7286563599769526e-12,
      4.429547652341005e-13,
      0.0,
      0.0,
      0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 1.173171688589058e-14,
     'k_biofouling': 3.858024691358025e-07,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 0,
     'k_rising': 1.0346349934254308e-06,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'dB1_Utopia',
    'RateConstants': {'k_discorporation': 1.6577456266495105e-09,
     'k_fragmentation': [2.8143863872716362e-11,
      1.7700197716954022e-12,
      1.7700197716954004e-12,
      0.0,
      0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 7.737992681559413e-11,
     'k_biofouling': 3.858024691358025e-07,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 0,
     'k_rising': 0.0001051098904486697,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'eB1_Utopia',
    'RateConstants': {'k_discorporation': 1.6577422529035748e-07,
     'k_fragmentation': [2.902884421962483e-10,
      1.327513477930999e-11,
      8.850089852873329e-12,
      4.425044926436635e-12,
      0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 7.46386097485203e-07,
     'k_biofouling': 3.858024691358025e-07,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 0,
     'k_rising': 0.01051115386238298,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'aC1_Utopia',
    'RateConstants': {'k_discorporation': 2.988444176099493e-11,
     'k_fragmentation': [0.0, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 1.1118274452903358e-06,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 4.5504679335615914e-07,
     'k_rising': 0,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'bC1_Utopia',
    'RateConstants': {'k_discorporation': 5.04871197766696e-11,
     'k_fragmentation': [6.18194361451919e-11, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 2.853660739944581e-06,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 7.531642076940026e-07,
     'k_rising': 0,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'cC1_Utopia',
    'RateConstants': {'k_discorporation': 5.519235687990294e-10,
     'k_fragmentation': [1.7585030442121013e-10,
      2.8546551868444204e-11,
      0.0,
      0.0,
      0.0],
     'k_heteroaggregation': 0.00010849780464794985,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 3.6767604382120297e-06,
     'k_rising': 0,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'dC1_Utopia',
    'RateConstants': {'k_discorporation': 3.5107254945583966e-08,
     'k_fragmentation': [1.4480321990500671e-09,
      9.106942934210595e-11,
      9.106942934210586e-11,
      0.0,
      0.0],
     'k_heteroaggregation': 0.09148973937909378,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 0,
     'k_rising': 5.8177198223276805e-05,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'eC1_Utopia',
    'RateConstants': {'k_discorporation': 3.3347572573695644e-06,
     'k_fragmentation': [1.4556546799246439e-08,
      6.656831364670411e-10,
      4.437887576446942e-10,
      2.2189437882234564e-10,
      0.0],
     'k_heteroaggregation': 1434.3744986195652,
     'k_heteroaggregate_breackup': 0,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 0,
     'k_rising': 0.010041157198282594,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'aD1_Utopia',
    'RateConstants': {'k_discorporation': 3.2093814175757388e-12,
     'k_fragmentation': [0.0, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 1.2693617996055035e-15,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 4.886908547352758e-07,
     'k_rising': 0,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'bD1_Utopia',
    'RateConstants': {'k_discorporation': 5.220346773537429e-12,
     'k_fragmentation': [6.286145344476081e-13, 0.0, 0.0, 0.0, 0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 3.0367536838492283e-15,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 7.795591107063965e-07,
     'k_rising': 0,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'cD1_Utopia',
    'RateConstants': {'k_discorporation': 5.5244693805308e-11,
     'k_fragmentation': [1.7593366092191516e-12,
      2.8560083495123953e-13,
      0.0,
      0.0,
      0.0],
     'k_heteroaggregation': 0,
     'k_heteroaggregate_breackup': 1.0888997964139593e-13,
     'k_biofouling': 0,
     'k_defouling': 0,
     'k_advective_transport': 1.371165644171779e-08,
     'k_settling': 3.686970030065211e-06,
     'k_rising': 0,
     'k_mixing': [0.000138, 3.167e-10]}},
   {'Pcode': 'dD1_Utopia',